from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass(frozen=True)
class PatternDef:
    name: str
    line_count: int
    rhyme_scheme: str  # normalized scheme like ABAB, XAXA, XXXX
    stability: float
    description: str
    emotion: str
    length_pattern: Optional[str] = None  # e.g., "common_meter" or "matched"


# NOTE: Stability values are heuristic numeric encodings of canon ordering.
PATTERNS: Dict[str, PatternDef] = {
    # 2-line
    "2_AA": PatternDef(
        name="2_AA",
        line_count=2,
        rhyme_scheme="AA",
        stability=1.0,
        description="Rhymed couplet - stops completely",
        emotion="Resolution, certainty",
        length_pattern="matched",
    ),
    "2_AA_UNMATCHED": PatternDef(
        name="2_AA_UNMATCHED",
        line_count=2,
        rhyme_scheme="AA",
        stability=0.6,
        description="Rhymed but unmatched lengths; less stable and pushes forward",
        emotion="Forward lean",
        length_pattern="unmatched",
    ),
    "2_XX": PatternDef(
        name="2_XX",
        line_count=2,
        rhyme_scheme="XX",
        stability=0.8,
        description="Unrhymed couplet - balanced but waiting",
        emotion="Calm anticipation",
        length_pattern="matched",
    ),
    "2_XX_UNMATCHED": PatternDef(
        name="2_XX_UNMATCHED",
        line_count=2,
        rhyme_scheme="XX",
        stability=0.35,
        description="Unrhymed and unmatched lengths; least stable 2-line unit",
        emotion="Leaning forward",
        length_pattern="unmatched",
    ),
    # 3-line
    "3_AAA": PatternDef(
        name="3_AAA",
        line_count=3,
        rhyme_scheme="AAA",
        stability=0.7,
        description="Triple rhyme - almost closes but expects a fourth line",
        emotion="Near completion, slight lean",
    ),
    "3_ABB": PatternDef(
        name="3_ABB",
        line_count=3,
        rhyme_scheme="ABB",
        stability=0.6,
        description="Opens then closes with a couplet",
        emotion="Departure then return",
    ),
    "3_XAA": PatternDef(
        name="3_XAA",
        line_count=3,
        rhyme_scheme="XAA",
        stability=0.5,
        description="Closure from nothing; surprise resolution",
        emotion="Discovery, emergence of order",
    ),
    "3_XXA": PatternDef(
        name="3_XXA",
        line_count=3,
        rhyme_scheme="XXA",
        stability=0.5,
        description="Floats; minimal expectations raised",
        emotion="Suspended, floating",
    ),
    "3_AAB": PatternDef(
        name="3_AAB",
        line_count=3,
        rhyme_scheme="AAB",
        stability=0.4,
        description="Leans forward; B targets next section",
        emotion="Anticipation",
    ),
    "3_ABA": PatternDef(
        name="3_ABA",
        line_count=3,
        rhyme_scheme="ABA",
        stability=0.2,
        description="Most unstable 3-line pattern; cries out for a fourth",
        emotion="Urgent need for resolution",
    ),
    "3_AXA": PatternDef(
        name="3_AXA",
        line_count=3,
        rhyme_scheme="AXA",
        stability=0.3,
        description="Frame with a gap; creates distance",
        emotion="Suspended, floating",
    ),
    # 4-line
    "4_AAAA": PatternDef(
        name="4_AAAA",
        line_count=4,
        rhyme_scheme="AAAA",
        stability=1.0,
        description="Maximum stability; stops twice (2 and 4)",
        emotion="Absolute certainty",
    ),
    "4_AABB": PatternDef(
        name="4_AABB",
        line_count=4,
        rhyme_scheme="AABB",
        stability=0.95,
        description="Two couplets; very stable",
        emotion="Organized, balanced",
    ),
    "4_ABAB": PatternDef(
        name="4_ABAB",
        line_count=4,
        rhyme_scheme="ABAB",
        stability=0.9,
        description="Common meter rhyme scaffold; resolved with forward motion",
        emotion="Satisfying resolution",
        length_pattern="common_meter",
    ),
    "4_XAXA": PatternDef(
        name="4_XAXA",
        line_count=4,
        rhyme_scheme="XAXA",
        stability=0.75,
        description="Less urgent than ABAB",
        emotion="Relaxed movement",
        length_pattern="common_meter",
    ),
    "4_ABAA": PatternDef(
        name="4_ABAA",
        line_count=4,
        rhyme_scheme="ABAA",
        stability=0.85,
        description="Deceptive resolution; spotlights last line",
        emotion="Surprise spotlight",
    ),
    "4_XXAA": PatternDef(
        name="4_XXAA",
        line_count=4,
        rhyme_scheme="XXAA",
        stability=0.6,
        description="Unexpected closure; resolution from chaos",
        emotion="Surprise relief",
    ),
    "4_AABA": PatternDef(
        name="4_AABA",
        line_count=4,
        rhyme_scheme="AABA",
        stability=0.5,
        description="Unstable; B targets next section",
        emotion="Longing",
    ),
    "4_ABBA": PatternDef(
        name="4_ABBA",
        line_count=4,
        rhyme_scheme="ABBA",
        stability=0.4,
        description="In Memoriam quatrain; floats",
        emotion="Wistful suspension",
    ),
    "4_XAAA": PatternDef(
        name="4_XAAA",
        line_count=4,
        rhyme_scheme="XAAA",
        stability=0.55,
        description="Stable but decreasing; mild instability from odd A count",
        emotion="Mostly stable with slight lean",
    ),
    "4_AXAX": PatternDef(
        name="4_AXAX",
        line_count=4,
        rhyme_scheme="AXAX",
        stability=0.5,
        description="Floating; few expectations raised",
        emotion="Waiting",
    ),
    "4_XAAX": PatternDef(
        name="4_XAAX",
        line_count=4,
        rhyme_scheme="XAAX",
        stability=0.45,
        description="Floats; internal couplet reduces expectations",
        emotion="Suspended, less urgent",
    ),
    "4_AAAB": PatternDef(
        name="4_AAAB",
        line_count=4,
        rhyme_scheme="AAAB",
        stability=0.35,
        description="Unstable; expects another A or a matching section",
        emotion="Unfinished business",
    ),
    "4_XXXX": PatternDef(
        name="4_XXXX",
        line_count=4,
        rhyme_scheme="XXXX",
        stability=0.2,
        description="Most unstable 4-line unit; unsettled",
        emotion="Unresolved instability",
    ),

    # 5-line (partial coverage; expand toward full canon)
    "5_AAAAA": PatternDef(
        name="5_AAAAA",
        line_count=5,
        rhyme_scheme="AAAAA",
        stability=0.7,
        description="Unexpected closure at line 5; emphatic title repetition",
        emotion="Building emphasis",
    ),
    "5_XAAAA": PatternDef(
        name="5_XAAAA",
        line_count=5,
        rhyme_scheme="XAAAA",
        stability=0.65,
        description="Leapfrog expectations; line 4 resolves then line 5 surprises",
        emotion="Order emerging",
    ),
    "5_XXAAA": PatternDef(
        name="5_XXAAA",
        line_count=5,
        rhyme_scheme="XXAAA",
        stability=0.6,
        description="Unexpected closure at line 4; line 5 pushes forward",
        emotion="Surprise then motion",
    ),
    "5_XAXAA": PatternDef(
        name="5_XAXAA",
        line_count=5,
        rhyme_scheme="XAXAA",
        stability=0.7,
        description="Pretty stable; resolution at line 4 can surprise",
        emotion="Stable with twist",
    ),
    "5_XXXAA": PatternDef(
        name="5_XXXAA",
        line_count=5,
        rhyme_scheme="XXXAA",
        stability=0.55,
        description="Floats then resolves unexpectedly at the end",
        emotion="Discovery",
    ),
    "5_ABABB": PatternDef(
        name="5_ABABB",
        line_count=5,
        rhyme_scheme="ABABB",
        stability=0.8,
        description="Deceptive closure at 4; completion at 5",
        emotion="Surprise then satisfaction",
    ),
    "5_ABABA": PatternDef(
        name="5_ABABA",
        line_count=5,
        rhyme_scheme="ABABA",
        stability=0.6,
        description="Alternation continues past expected closure; seeks 6th",
        emotion="Continuing motion",
    ),
    "5_AABBA": PatternDef(
        name="5_AABBA",
        line_count=5,
        rhyme_scheme="AABBA",
        stability=0.75,
        description="Limerick structure; spotlight at line 5",
        emotion="Playful timing",
    ),
    "5_ABBAB": PatternDef(
        name="5_ABBAB",
        line_count=5,
        rhyme_scheme="ABBAB",
        stability=0.65,
        description="Starts second ABB sequence; mildly unstable",
        emotion="Continuing motion",
    ),
    "5_AABBB": PatternDef(
        name="5_AABBB",
        line_count=5,
        rhyme_scheme="AABBB",
        stability=0.75,
        description="Pretty stable; resolutions at each couplet",
        emotion="Steady with emphasis",
    ),
    "5_AAABB": PatternDef(
        name="5_AAABB",
        line_count=5,
        rhyme_scheme="AAABB",
        stability=0.7,
        description="Strangely stable; couplet softens push forward",
        emotion="Stable with mild lean",
    ),

    # 5-line: canon "3 matching elements" group (represented as X for singleton rhyme classes)
    "5_AXBAB": PatternDef(
        name="5_AXBAB",
        line_count=5,
        rhyme_scheme="AXBAB",
        stability=0.7,
        description="Stable with mild surprise at line 5 (canon ABCAC)",
        emotion="Stable with twist",
    ),
    "5_ABCAC": PatternDef(
        name="5_ABCAC",
        line_count=5,
        rhyme_scheme="ABCAC",
        stability=0.7,
        description="Stable with mild surprise at line 5",
        emotion="Stable with twist",
    ),
    "5_XABAB": PatternDef(
        name="5_XABAB",
        line_count=5,
        rhyme_scheme="XABAB",
        stability=0.7,
        description="Stable; deceptive closure at line 5 (canon ABCBC)",
        emotion="Stable with deceptive closure",
    ),
    "5_ABCBC": PatternDef(
        name="5_ABCBC",
        line_count=5,
        rhyme_scheme="ABCBC",
        stability=0.7,
        description="Stable; deceptive closure at line 5",
        emotion="Stable with deceptive closure",
    ),
    "5_ABCBB": PatternDef(
        name="5_ABCBB",
        line_count=5,
        rhyme_scheme="ABCBB",
        stability=0.65,
        description="Stable with spotlight when the singleton line sticks out",
        emotion="Spotlight / surprise",
    ),
    "5_ABXAB": PatternDef(
        name="5_ABXAB",
        line_count=5,
        rhyme_scheme="ABXAB",
        stability=0.4,
        description="Unstable; pushes forward hard (canon ABCAB)",
        emotion="Forward drive",
    ),
    "5_ABCAB": PatternDef(
        name="5_ABCAB",
        line_count=5,
        rhyme_scheme="ABCAB",
        stability=0.4,
        description="Unstable; pushes forward hard",
        emotion="Forward drive",
    ),

    # 6-line
    "6_ABABAB": PatternDef(
        name="6_ABABAB",
        line_count=6,
        rhyme_scheme="ABABAB",
        stability=0.9,
        description="Extended common-meter alternation; resolves at 6",
        emotion="Relentless forward motion then release",
        length_pattern="common_meter",
    ),
    "6_ABABCC": PatternDef(
        name="6_ABABCC",
        line_count=6,
        rhyme_scheme="ABABCC",
        stability=0.95,
        description="Common meter plus closing couplet; very stable",
        emotion="Development then emphatic conclusion",
        length_pattern="common_meter",
    ),
    "6_ABCABC": PatternDef(
        name="6_ABCABC",
        line_count=6,
        rhyme_scheme="ABCABC",
        stability=0.95,
        description="Six-line common meter; strong forward motion to satisfying resolution",
        emotion="Building urgency then release",
        length_pattern="common_meter",
    ),
    "6_ABABAA": PatternDef(
        name="6_ABABAA",
        line_count=6,
        rhyme_scheme="ABABAA",
        stability=0.95,
        description="Very stable; closes at line 4, final couplet finishes",
        emotion="Strong arrival",
    ),
    "6_AABAAB": PatternDef(
        name="6_AABAAB",
        line_count=6,
        rhyme_scheme="AABAAB",
        stability=0.9,
        description="Two matched AAB units (Cohen-style); sophisticated balance",
        emotion="Balanced, meditative",
    ),

    "6_AABCCB": PatternDef(
        name="6_AABCCB",
        line_count=6,
        rhyme_scheme="AABCCB",
        stability=0.85,
        description="Couplet, new couplet, return to B - creates arc",
        emotion="Journey and return",
    ),
    "6_AABBCC": PatternDef(
        name="6_AABBCC",
        line_count=6,
        rhyme_scheme="AABBCC",
        stability=0.9,
        description="Two couplets, then a closing couplet; very stable",
        emotion="Development then emphatic conclusion",
    ),
}


def patterns_for_line_count(n: int) -> List[PatternDef]:
    return [p for p in PATTERNS.values() if p.line_count == n]
