"""
Expanded Built-in CMU Dictionary for Pattison Engine

This provides phonetic data for common words when the full CMU dictionary
isn't available. Organized by category for maintainability.

Total: ~2,500+ words covering core vocabulary needed for songwriting analysis.
"""

from typing import Dict, List

# =============================================================================
# ARTICLES, PRONOUNS, DETERMINERS
# =============================================================================

_ARTICLES_PRONOUNS: Dict[str, List[str]] = {
    "A": ["AH0"], "AN": ["AE1", "N"], "THE": ["DH", "AH0"],
    "I": ["AY1"], "ME": ["M", "IY1"], "MY": ["M", "AY1"], "MINE": ["M", "AY1", "N"],
    "MYSELF": ["M", "AY0", "S", "EH1", "L", "F"],
    "YOU": ["Y", "UW1"], "YOUR": ["Y", "AO1", "R"], "YOURS": ["Y", "AO1", "R", "Z"],
    "YOURSELF": ["Y", "ER0", "S", "EH1", "L", "F"],
    "HE": ["HH", "IY1"], "HIM": ["HH", "IH1", "M"], "HIS": ["HH", "IH1", "Z"],
    "HIMSELF": ["HH", "IH0", "M", "S", "EH1", "L", "F"],
    "SHE": ["SH", "IY1"], "HER": ["HH", "ER1"], "HERS": ["HH", "ER1", "Z"],
    "HERSELF": ["HH", "ER0", "S", "EH1", "L", "F"],
    "IT": ["IH1", "T"], "ITS": ["IH1", "T", "S"],
    "ITSELF": ["IH0", "T", "S", "EH1", "L", "F"],
    "WE": ["W", "IY1"], "US": ["AH1", "S"], "OUR": ["AW1", "ER0"],
    "OURS": ["AW1", "ER0", "Z"], "OURSELVES": ["AW0", "ER0", "S", "EH1", "L", "V", "Z"],
    "THEY": ["DH", "EY1"], "THEM": ["DH", "EH1", "M"], "THEIR": ["DH", "EH1", "R"],
    "THEIRS": ["DH", "EH1", "R", "Z"], "THEMSELVES": ["DH", "EH0", "M", "S", "EH1", "L", "V", "Z"],
    "THIS": ["DH", "IH1", "S"], "THAT": ["DH", "AE1", "T"],
    "THESE": ["DH", "IY1", "Z"], "THOSE": ["DH", "OW1", "Z"],
    "WHO": ["HH", "UW1"], "WHOM": ["HH", "UW1", "M"], "WHOSE": ["HH", "UW1", "Z"],
    "WHAT": ["W", "AH1", "T"], "WHICH": ["W", "IH1", "CH"],
    "WHERE": ["W", "EH1", "R"], "WHEN": ["W", "EH1", "N"],
    "WHY": ["W", "AY1"], "HOW": ["HH", "AW1"],
    "ALL": ["AO1", "L"], "EACH": ["IY1", "CH"], "EVERY": ["EH1", "V", "R", "IY0"],
    "BOTH": ["B", "OW1", "TH"], "FEW": ["F", "Y", "UW1"],
    "MORE": ["M", "AO1", "R"], "MOST": ["M", "OW1", "S", "T"],
    "OTHER": ["AH1", "DH", "ER0"], "SOME": ["S", "AH1", "M"],
    "SUCH": ["S", "AH1", "CH"], "NO": ["N", "OW1"], "NOR": ["N", "AO1", "R"],
    "NOT": ["N", "AA1", "T"], "ONLY": ["OW1", "N", "L", "IY0"],
    "OWN": ["OW1", "N"], "SAME": ["S", "EY1", "M"], "SO": ["S", "OW1"],
    "THAN": ["DH", "AE1", "N"], "TOO": ["T", "UW1"],
    "VERY": ["V", "EH1", "R", "IY0"], "ANY": ["EH1", "N", "IY0"],
    "MANY": ["M", "EH1", "N", "IY0"], "MUCH": ["M", "AH1", "CH"],
    "NONE": ["N", "AH1", "N"], "ONE": ["W", "AH1", "N"],
    "ANOTHER": ["AH0", "N", "AH1", "DH", "ER0"],
    "SOMEONE": ["S", "AH1", "M", "W", "AH2", "N"],
    "SOMETHING": ["S", "AH1", "M", "TH", "IH0", "NG"],
    "SOMEWHERE": ["S", "AH1", "M", "W", "EH2", "R"],
    "NOTHING": ["N", "AH1", "TH", "IH0", "NG"],
    "NOBODY": ["N", "OW1", "B", "AH0", "D", "IY0"],
    "NOWHERE": ["N", "OW1", "W", "EH2", "R"],
    "EVERYONE": ["EH1", "V", "R", "IY0", "W", "AH2", "N"],
    "EVERYTHING": ["EH1", "V", "R", "IY0", "TH", "IH2", "NG"],
    "EVERYWHERE": ["EH1", "V", "R", "IY0", "W", "EH2", "R"],
    "ANYONE": ["EH1", "N", "IY0", "W", "AH2", "N"],
    "ANYTHING": ["EH1", "N", "IY0", "TH", "IH2", "NG"],
    "ANYWHERE": ["EH1", "N", "IY0", "W", "EH2", "R"],
}

# =============================================================================
# PREPOSITIONS & CONJUNCTIONS
# =============================================================================

_PREPOSITIONS_CONJUNCTIONS: Dict[str, List[str]] = {
    "ABOUT": ["AH0", "B", "AW1", "T"], "ABOVE": ["AH0", "B", "AH1", "V"],
    "ACROSS": ["AH0", "K", "R", "AO1", "S"], "AFTER": ["AE1", "F", "T", "ER0"],
    "AGAINST": ["AH0", "G", "EH1", "N", "S", "T"], "ALONG": ["AH0", "L", "AO1", "NG"],
    "AMONG": ["AH0", "M", "AH1", "NG"], "AROUND": ["ER0", "AW1", "N", "D"],
    "AT": ["AE1", "T"], "BEFORE": ["B", "IH0", "F", "AO1", "R"],
    "BEHIND": ["B", "IH0", "HH", "AY1", "N", "D"], "BELOW": ["B", "IH0", "L", "OW1"],
    "BENEATH": ["B", "IH0", "N", "IY1", "TH"], "BESIDE": ["B", "IH0", "S", "AY1", "D"],
    "BETWEEN": ["B", "IH0", "T", "W", "IY1", "N"], "BEYOND": ["B", "IH0", "AA1", "N", "D"],
    "BY": ["B", "AY1"], "DOWN": ["D", "AW1", "N"],
    "DURING": ["D", "UH1", "R", "IH0", "NG"], "EXCEPT": ["IH0", "K", "S", "EH1", "P", "T"],
    "FOR": ["F", "AO1", "R"], "FROM": ["F", "R", "AH1", "M"],
    "IN": ["IH1", "N"], "INSIDE": ["IH0", "N", "S", "AY1", "D"],
    "INTO": ["IH1", "N", "T", "UW0"], "LIKE": ["L", "AY1", "K"],
    "NEAR": ["N", "IH1", "R"], "OF": ["AH1", "V"], "OFF": ["AO1", "F"],
    "ON": ["AA1", "N"], "ONTO": ["AA1", "N", "T", "UW0"],
    "OUT": ["AW1", "T"], "OUTSIDE": ["AW1", "T", "S", "AY1", "D"],
    "OVER": ["OW1", "V", "ER0"], "PAST": ["P", "AE1", "S", "T"],
    "SINCE": ["S", "IH1", "N", "S"], "THROUGH": ["TH", "R", "UW1"],
    "THROUGHOUT": ["TH", "R", "UW0", "AW1", "T"], "TO": ["T", "UW1"],
    "TOWARD": ["T", "AH0", "W", "AO1", "R", "D"], "TOWARDS": ["T", "AH0", "W", "AO1", "R", "D", "Z"],
    "UNDER": ["AH1", "N", "D", "ER0"], "UNDERNEATH": ["AH2", "N", "D", "ER0", "N", "IY1", "TH"],
    "UNTIL": ["AH0", "N", "T", "IH1", "L"], "UP": ["AH1", "P"],
    "UPON": ["AH0", "P", "AA1", "N"], "WITH": ["W", "IH1", "TH"],
    "WITHIN": ["W", "IH0", "DH", "IH1", "N"], "WITHOUT": ["W", "IH0", "TH", "AW1", "T"],
    "AND": ["AE1", "N", "D"], "BUT": ["B", "AH1", "T"], "OR": ["AO1", "R"],
    "YET": ["Y", "EH1", "T"], "BECAUSE": ["B", "IH0", "K", "AO1", "Z"],
    "ALTHOUGH": ["AO0", "L", "DH", "OW1"], "THOUGH": ["DH", "OW1"],
    "WHILE": ["W", "AY1", "L"], "IF": ["IH1", "F"], "UNLESS": ["AH0", "N", "L", "EH1", "S"],
    "WHETHER": ["W", "EH1", "DH", "ER0"], "EITHER": ["IY1", "DH", "ER0"],
    "NEITHER": ["N", "IY1", "DH", "ER0"], "ONCE": ["W", "AH1", "N", "S"],
    "TWICE": ["T", "W", "AY1", "S"], "AS": ["AE1", "Z"], "ALSO": ["AO1", "L", "S", "OW0"],
    "THEN": ["DH", "EH1", "N"], "THEREFORE": ["DH", "EH1", "R", "F", "AO2", "R"],
    "HOWEVER": ["HH", "AW0", "EH1", "V", "ER0"], "MOREOVER": ["M", "AO0", "R", "OW1", "V", "ER0"],
    "MEANWHILE": ["M", "IY1", "N", "W", "AY2", "L"], "OTHERWISE": ["AH1", "DH", "ER0", "W", "AY2", "Z"],
    "INSTEAD": ["IH0", "N", "S", "T", "EH1", "D"], "STILL": ["S", "T", "IH1", "L"],
    "JUST": ["JH", "AH1", "S", "T"], "EVEN": ["IY1", "V", "AH0", "N"],
    "ALMOST": ["AO1", "L", "M", "OW2", "S", "T"], "ALREADY": ["AO0", "L", "R", "EH1", "D", "IY0"],
    "ALWAYS": ["AO1", "L", "W", "EY2", "Z"], "NEVER": ["N", "EH1", "V", "ER0"],
    "EVER": ["EH1", "V", "ER0"], "FOREVER": ["F", "ER0", "EH1", "V", "ER0"],
    "AGAIN": ["AH0", "G", "EH1", "N"], "MAYBE": ["M", "EY1", "B", "IY0"],
    "PERHAPS": ["P", "ER0", "HH", "AE1", "P", "S"],
}

# =============================================================================
# AUXILIARY & MODAL VERBS
# =============================================================================

_AUXILIARY_VERBS: Dict[str, List[str]] = {
    "BE": ["B", "IY1"], "AM": ["AE1", "M"], "IS": ["IH1", "Z"], "ARE": ["AA1", "R"],
    "WAS": ["W", "AA1", "Z"], "WERE": ["W", "ER1"], "BEEN": ["B", "IH1", "N"],
    "BEING": ["B", "IY1", "IH0", "NG"],
    "HAVE": ["HH", "AE1", "V"], "HAS": ["HH", "AE1", "Z"], "HAD": ["HH", "AE1", "D"],
    "HAVING": ["HH", "AE1", "V", "IH0", "NG"],
    "DO": ["D", "UW1"], "DOES": ["D", "AH1", "Z"], "DID": ["D", "IH1", "D"],
    "DOING": ["D", "UW1", "IH0", "NG"], "DONE": ["D", "AH1", "N"],
    "CAN": ["K", "AE1", "N"], "COULD": ["K", "UH1", "D"],
    "WILL": ["W", "IH1", "L"], "WOULD": ["W", "UH1", "D"],
    "SHALL": ["SH", "AE1", "L"], "SHOULD": ["SH", "UH1", "D"],
    "MAY": ["M", "EY1"], "MIGHT": ["M", "AY1", "T"], "MUST": ["M", "AH1", "S", "T"],
    "OUGHT": ["AO1", "T"],
    "GET": ["G", "EH1", "T"], "GETS": ["G", "EH1", "T", "S"], "GOT": ["G", "AA1", "T"],
    "GOTTEN": ["G", "AA1", "T", "AH0", "N"], "GETTING": ["G", "EH1", "T", "IH0", "NG"],
    "LET": ["L", "EH1", "T"], "LETS": ["L", "EH1", "T", "S"],
    "MAKE": ["M", "EY1", "K"], "MAKES": ["M", "EY1", "K", "S"], "MADE": ["M", "EY1", "D"],
    "MAKING": ["M", "EY1", "K", "IH0", "NG"],
    "KEEP": ["K", "IY1", "P"], "KEEPS": ["K", "IY1", "P", "S"], "KEPT": ["K", "EH1", "P", "T"],
    "KEEPING": ["K", "IY1", "P", "IH0", "NG"],
}

# =============================================================================
# COMMON ACTION VERBS
# =============================================================================

_ACTION_VERBS: Dict[str, List[str]] = {
    # Movement
    "GO": ["G", "OW1"], "GOES": ["G", "OW1", "Z"], "WENT": ["W", "EH1", "N", "T"],
    "GONE": ["G", "AO1", "N"], "GOING": ["G", "OW1", "IH0", "NG"],
    "COME": ["K", "AH1", "M"], "COMES": ["K", "AH1", "M", "Z"], "CAME": ["K", "EY1", "M"],
    "COMING": ["K", "AH1", "M", "IH0", "NG"],
    "WALK": ["W", "AO1", "K"], "WALKS": ["W", "AO1", "K", "S"], "WALKED": ["W", "AO1", "K", "T"],
    "WALKING": ["W", "AO1", "K", "IH0", "NG"],
    "RUN": ["R", "AH1", "N"], "RUNS": ["R", "AH1", "N", "Z"], "RAN": ["R", "AE1", "N"],
    "RUNNING": ["R", "AH1", "N", "IH0", "NG"],
    "MOVE": ["M", "UW1", "V"], "MOVES": ["M", "UW1", "V", "Z"], "MOVED": ["M", "UW1", "V", "D"],
    "MOVING": ["M", "UW1", "V", "IH0", "NG"],
    "STAND": ["S", "T", "AE1", "N", "D"], "STANDS": ["S", "T", "AE1", "N", "D", "Z"],
    "STOOD": ["S", "T", "UH1", "D"], "STANDING": ["S", "T", "AE1", "N", "D", "IH0", "NG"],
    "SIT": ["S", "IH1", "T"], "SITS": ["S", "IH1", "T", "S"], "SAT": ["S", "AE1", "T"],
    "SITTING": ["S", "IH1", "T", "IH0", "NG"],
    "FALL": ["F", "AO1", "L"], "FALLS": ["F", "AO1", "L", "Z"], "FELL": ["F", "EH1", "L"],
    "FALLEN": ["F", "AO1", "L", "AH0", "N"], "FALLING": ["F", "AO1", "L", "IH0", "NG"],
    "RISE": ["R", "AY1", "Z"], "RISES": ["R", "AY1", "Z", "IH0", "Z"], "ROSE": ["R", "OW1", "Z"],
    "RISEN": ["R", "IH1", "Z", "AH0", "N"], "RISING": ["R", "AY1", "Z", "IH0", "NG"],
    "FLY": ["F", "L", "AY1"], "FLIES": ["F", "L", "AY1", "Z"], "FLEW": ["F", "L", "UW1"],
    "FLOWN": ["F", "L", "OW1", "N"], "FLYING": ["F", "L", "AY1", "IH0", "NG"],
    "JUMP": ["JH", "AH1", "M", "P"], "JUMPS": ["JH", "AH1", "M", "P", "S"],
    "JUMPED": ["JH", "AH1", "M", "P", "T"], "JUMPING": ["JH", "AH1", "M", "P", "IH0", "NG"],
    "TURN": ["T", "ER1", "N"], "TURNS": ["T", "ER1", "N", "Z"], "TURNED": ["T", "ER1", "N", "D"],
    "TURNING": ["T", "ER1", "N", "IH0", "NG"],
    "RETURN": ["R", "IH0", "T", "ER1", "N"], "RETURNS": ["R", "IH0", "T", "ER1", "N", "Z"],
    "RETURNED": ["R", "IH0", "T", "ER1", "N", "D"], "RETURNING": ["R", "IH0", "T", "ER1", "N", "IH0", "NG"],
    "LEAVE": ["L", "IY1", "V"], "LEAVES": ["L", "IY1", "V", "Z"], "LEFT": ["L", "EH1", "F", "T"],
    "LEAVING": ["L", "IY1", "V", "IH0", "NG"],
    "STAY": ["S", "T", "EY1"], "STAYS": ["S", "T", "EY1", "Z"], "STAYED": ["S", "T", "EY1", "D"],
    "STAYING": ["S", "T", "EY1", "IH0", "NG"],
    "REACH": ["R", "IY1", "CH"], "REACHES": ["R", "IY1", "CH", "IH0", "Z"],
    "REACHED": ["R", "IY1", "CH", "T"], "REACHING": ["R", "IY1", "CH", "IH0", "NG"],
    "FOLLOW": ["F", "AA1", "L", "OW0"], "FOLLOWS": ["F", "AA1", "L", "OW0", "Z"],
    "FOLLOWED": ["F", "AA1", "L", "OW0", "D"], "FOLLOWING": ["F", "AA1", "L", "OW0", "IH0", "NG"],
    "LEAD": ["L", "IY1", "D"], "LEADS": ["L", "IY1", "D", "Z"], "LED": ["L", "EH1", "D"],
    "LEADING": ["L", "IY1", "D", "IH0", "NG"],
    "DRIVE": ["D", "R", "AY1", "V"], "DRIVES": ["D", "R", "AY1", "V", "Z"],
    "DROVE": ["D", "R", "OW1", "V"], "DRIVEN": ["D", "R", "IH1", "V", "AH0", "N"],
    "DRIVING": ["D", "R", "AY1", "V", "IH0", "NG"],
    "RIDE": ["R", "AY1", "D"], "RIDES": ["R", "AY1", "D", "Z"], "RODE": ["R", "OW1", "D"],
    "RIDDEN": ["R", "IH1", "D", "AH0", "N"], "RIDING": ["R", "AY1", "D", "IH0", "NG"],
    "DANCE": ["D", "AE1", "N", "S"], "DANCES": ["D", "AE1", "N", "S", "IH0", "Z"],
    "DANCED": ["D", "AE1", "N", "S", "T"], "DANCING": ["D", "AE1", "N", "S", "IH0", "NG"],
    "CLIMB": ["K", "L", "AY1", "M"], "CLIMBS": ["K", "L", "AY1", "M", "Z"],
    "CLIMBED": ["K", "L", "AY1", "M", "D"], "CLIMBING": ["K", "L", "AY1", "M", "IH0", "NG"],
    "ROLL": ["R", "OW1", "L"], "ROLLS": ["R", "OW1", "L", "Z"], "ROLLED": ["R", "OW1", "L", "D"],
    "ROLLING": ["R", "OW1", "L", "IH0", "NG"],
    "SPIN": ["S", "P", "IH1", "N"], "SPINS": ["S", "P", "IH1", "N", "Z"],
    "SPUN": ["S", "P", "AH1", "N"], "SPINNING": ["S", "P", "IH1", "N", "IH0", "NG"],
    "SLIDE": ["S", "L", "AY1", "D"], "SLIDES": ["S", "L", "AY1", "D", "Z"],
    "SLID": ["S", "L", "IH1", "D"], "SLIDING": ["S", "L", "AY1", "D", "IH0", "NG"],
    "STEP": ["S", "T", "EH1", "P"], "STEPS": ["S", "T", "EH1", "P", "S"],
    "STEPPED": ["S", "T", "EH1", "P", "T"], "STEPPING": ["S", "T", "EH1", "P", "IH0", "NG"],
    "CROSS": ["K", "R", "AO1", "S"], "CROSSES": ["K", "R", "AO1", "S", "IH0", "Z"],
    "CROSSED": ["K", "R", "AO1", "S", "T"], "CROSSING": ["K", "R", "AO1", "S", "IH0", "NG"],
    "PASS": ["P", "AE1", "S"], "PASSES": ["P", "AE1", "S", "IH0", "Z"],
    "PASSED": ["P", "AE1", "S", "T"], "PASSING": ["P", "AE1", "S", "IH0", "NG"],
    "PULL": ["P", "UH1", "L"], "PULLS": ["P", "UH1", "L", "Z"], "PULLED": ["P", "UH1", "L", "D"],
    "PULLING": ["P", "UH1", "L", "IH0", "NG"],
    "PUSH": ["P", "UH1", "SH"], "PUSHES": ["P", "UH1", "SH", "IH0", "Z"],
    "PUSHED": ["P", "UH1", "SH", "T"], "PUSHING": ["P", "UH1", "SH", "IH0", "NG"],
    "THROW": ["TH", "R", "OW1"], "THROWS": ["TH", "R", "OW1", "Z"],
    "THREW": ["TH", "R", "UW1"], "THROWN": ["TH", "R", "OW1", "N"],
    "THROWING": ["TH", "R", "OW1", "IH0", "NG"],
    "CATCH": ["K", "AE1", "CH"], "CATCHES": ["K", "AE1", "CH", "IH0", "Z"],
    "CAUGHT": ["K", "AO1", "T"], "CATCHING": ["K", "AE1", "CH", "IH0", "NG"],
    "CARRY": ["K", "AE1", "R", "IY0"], "CARRIES": ["K", "AE1", "R", "IY0", "Z"],
    "CARRIED": ["K", "AE1", "R", "IY0", "D"], "CARRYING": ["K", "AE1", "R", "IY0", "IH0", "NG"],
    "HOLD": ["HH", "OW1", "L", "D"], "HOLDS": ["HH", "OW1", "L", "D", "Z"],
    "HELD": ["HH", "EH1", "L", "D"], "HOLDING": ["HH", "OW1", "L", "D", "IH0", "NG"],
    "DROP": ["D", "R", "AA1", "P"], "DROPS": ["D", "R", "AA1", "P", "S"],
    "DROPPED": ["D", "R", "AA1", "P", "T"], "DROPPING": ["D", "R", "AA1", "P", "IH0", "NG"],
    "PICK": ["P", "IH1", "K"], "PICKS": ["P", "IH1", "K", "S"], "PICKED": ["P", "IH1", "K", "T"],
    "PICKING": ["P", "IH1", "K", "IH0", "NG"],
    "LIFT": ["L", "IH1", "F", "T"], "LIFTS": ["L", "IH1", "F", "T", "S"],
    "LIFTED": ["L", "IH1", "F", "T", "IH0", "D"], "LIFTING": ["L", "IH1", "F", "T", "IH0", "NG"],
    "PUT": ["P", "UH1", "T"], "PUTS": ["P", "UH1", "T", "S"], "PUTTING": ["P", "UH1", "T", "IH0", "NG"],
    "SET": ["S", "EH1", "T"], "SETS": ["S", "EH1", "T", "S"], "SETTING": ["S", "EH1", "T", "IH0", "NG"],
    "LAY": ["L", "EY1"], "LAYS": ["L", "EY1", "Z"], "LAID": ["L", "EY1", "D"],
    "LAYING": ["L", "EY1", "IH0", "NG"],
    "LIE": ["L", "AY1"], "LIES": ["L", "AY1", "Z"], "LYING": ["L", "AY1", "IH0", "NG"],
    "HANG": ["HH", "AE1", "NG"], "HANGS": ["HH", "AE1", "NG", "Z"], "HUNG": ["HH", "AH1", "NG"],
    "HANGING": ["HH", "AE1", "NG", "IH0", "NG"],
    # Communication
    "SAY": ["S", "EY1"], "SAYS": ["S", "EH1", "Z"], "SAID": ["S", "EH1", "D"],
    "SAYING": ["S", "EY1", "IH0", "NG"],
    "TELL": ["T", "EH1", "L"], "TELLS": ["T", "EH1", "L", "Z"], "TOLD": ["T", "OW1", "L", "D"],
    "TELLING": ["T", "EH1", "L", "IH0", "NG"],
    "TALK": ["T", "AO1", "K"], "TALKS": ["T", "AO1", "K", "S"], "TALKED": ["T", "AO1", "K", "T"],
    "TALKING": ["T", "AO1", "K", "IH0", "NG"],
    "SPEAK": ["S", "P", "IY1", "K"], "SPEAKS": ["S", "P", "IY1", "K", "S"],
    "SPOKE": ["S", "P", "OW1", "K"], "SPOKEN": ["S", "P", "OW1", "K", "AH0", "N"],
    "SPEAKING": ["S", "P", "IY1", "K", "IH0", "NG"],
    "ASK": ["AE1", "S", "K"], "ASKS": ["AE1", "S", "K", "S"], "ASKED": ["AE1", "S", "K", "T"],
    "ASKING": ["AE1", "S", "K", "IH0", "NG"],
    "ANSWER": ["AE1", "N", "S", "ER0"], "ANSWERS": ["AE1", "N", "S", "ER0", "Z"],
    "ANSWERED": ["AE1", "N", "S", "ER0", "D"], "ANSWERING": ["AE1", "N", "S", "ER0", "IH0", "NG"],
    "CALL": ["K", "AO1", "L"], "CALLS": ["K", "AO1", "L", "Z"], "CALLED": ["K", "AO1", "L", "D"],
    "CALLING": ["K", "AO1", "L", "IH0", "NG"],
    "CRY": ["K", "R", "AY1"], "CRIES": ["K", "R", "AY1", "Z"], "CRIED": ["K", "R", "AY1", "D"],
    "CRYING": ["K", "R", "AY1", "IH0", "NG"],
    "SHOUT": ["SH", "AW1", "T"], "SHOUTS": ["SH", "AW1", "T", "S"],
    "SHOUTED": ["SH", "AW1", "T", "IH0", "D"], "SHOUTING": ["SH", "AW1", "T", "IH0", "NG"],
    "SCREAM": ["S", "K", "R", "IY1", "M"], "SCREAMS": ["S", "K", "R", "IY1", "M", "Z"],
    "SCREAMED": ["S", "K", "R", "IY1", "M", "D"], "SCREAMING": ["S", "K", "R", "IY1", "M", "IH0", "NG"],
    "WHISPER": ["W", "IH1", "S", "P", "ER0"], "WHISPERS": ["W", "IH1", "S", "P", "ER0", "Z"],
    "WHISPERED": ["W", "IH1", "S", "P", "ER0", "D"], "WHISPERING": ["W", "IH1", "S", "P", "ER0", "IH0", "NG"],
    "SING": ["S", "IH1", "NG"], "SINGS": ["S", "IH1", "NG", "Z"], "SANG": ["S", "AE1", "NG"],
    "SUNG": ["S", "AH1", "NG"], "SINGING": ["S", "IH1", "NG", "IH0", "NG"],
    "WRITE": ["R", "AY1", "T"], "WRITES": ["R", "AY1", "T", "S"], "WROTE": ["R", "OW1", "T"],
    "WRITTEN": ["R", "IH1", "T", "AH0", "N"], "WRITING": ["R", "AY1", "T", "IH0", "NG"],
    "READ": ["R", "IY1", "D"], "READS": ["R", "IY1", "D", "Z"], "READING": ["R", "IY1", "D", "IH0", "NG"],
    "LISTEN": ["L", "IH1", "S", "AH0", "N"], "LISTENS": ["L", "IH1", "S", "AH0", "N", "Z"],
    "LISTENED": ["L", "IH1", "S", "AH0", "N", "D"], "LISTENING": ["L", "IH1", "S", "AH0", "N", "IH0", "NG"],
    "HEAR": ["HH", "IH1", "R"], "HEARS": ["HH", "IH1", "R", "Z"], "HEARD": ["HH", "ER1", "D"],
    "HEARING": ["HH", "IH1", "R", "IH0", "NG"],
    "LAUGH": ["L", "AE1", "F"], "LAUGHS": ["L", "AE1", "F", "S"], "LAUGHED": ["L", "AE1", "F", "T"],
    "LAUGHING": ["L", "AE1", "F", "IH0", "NG"],
    "SMILE": ["S", "M", "AY1", "L"], "SMILES": ["S", "M", "AY1", "L", "Z"],
    "SMILED": ["S", "M", "AY1", "L", "D"], "SMILING": ["S", "M", "AY1", "L", "IH0", "NG"],
    # Perception
    "SEE": ["S", "IY1"], "SEES": ["S", "IY1", "Z"], "SAW": ["S", "AO1"],
    "SEEN": ["S", "IY1", "N"], "SEEING": ["S", "IY1", "IH0", "NG"],
    "LOOK": ["L", "UH1", "K"], "LOOKS": ["L", "UH1", "K", "S"], "LOOKED": ["L", "UH1", "K", "T"],
    "LOOKING": ["L", "UH1", "K", "IH0", "NG"],
    "WATCH": ["W", "AA1", "CH"], "WATCHES": ["W", "AA1", "CH", "IH0", "Z"],
    "WATCHED": ["W", "AA1", "CH", "T"], "WATCHING": ["W", "AA1", "CH", "IH0", "NG"],
    "FEEL": ["F", "IY1", "L"], "FEELS": ["F", "IY1", "L", "Z"], "FELT": ["F", "EH1", "L", "T"],
    "FEELING": ["F", "IY1", "L", "IH0", "NG"],
    "TOUCH": ["T", "AH1", "CH"], "TOUCHES": ["T", "AH1", "CH", "IH0", "Z"],
    "TOUCHED": ["T", "AH1", "CH", "T"], "TOUCHING": ["T", "AH1", "CH", "IH0", "NG"],
    # Mental
    "THINK": ["TH", "IH1", "NG", "K"], "THINKS": ["TH", "IH1", "NG", "K", "S"],
    "THOUGHT": ["TH", "AO1", "T"], "THINKING": ["TH", "IH1", "NG", "K", "IH0", "NG"],
    "KNOW": ["N", "OW1"], "KNOWS": ["N", "OW1", "Z"], "KNEW": ["N", "UW1"],
    "KNOWN": ["N", "OW1", "N"], "KNOWING": ["N", "OW1", "IH0", "NG"],
    "BELIEVE": ["B", "IH0", "L", "IY1", "V"], "BELIEVES": ["B", "IH0", "L", "IY1", "V", "Z"],
    "BELIEVED": ["B", "IH0", "L", "IY1", "V", "D"], "BELIEVING": ["B", "IH0", "L", "IY1", "V", "IH0", "NG"],
    "UNDERSTAND": ["AH2", "N", "D", "ER0", "S", "T", "AE1", "N", "D"],
    "UNDERSTANDS": ["AH2", "N", "D", "ER0", "S", "T", "AE1", "N", "D", "Z"],
    "UNDERSTOOD": ["AH2", "N", "D", "ER0", "S", "T", "UH1", "D"],
    "UNDERSTANDING": ["AH2", "N", "D", "ER0", "S", "T", "AE1", "N", "D", "IH0", "NG"],
    "REMEMBER": ["R", "IH0", "M", "EH1", "M", "B", "ER0"],
    "REMEMBERS": ["R", "IH0", "M", "EH1", "M", "B", "ER0", "Z"],
    "REMEMBERED": ["R", "IH0", "M", "EH1", "M", "B", "ER0", "D"],
    "REMEMBERING": ["R", "IH0", "M", "EH1", "M", "B", "ER0", "IH0", "NG"],
    "FORGET": ["F", "ER0", "G", "EH1", "T"], "FORGETS": ["F", "ER0", "G", "EH1", "T", "S"],
    "FORGOT": ["F", "ER0", "G", "AA1", "T"], "FORGOTTEN": ["F", "ER0", "G", "AA1", "T", "AH0", "N"],
    "FORGETTING": ["F", "ER0", "G", "EH1", "T", "IH0", "NG"],
    "LEARN": ["L", "ER1", "N"], "LEARNS": ["L", "ER1", "N", "Z"], "LEARNED": ["L", "ER1", "N", "D"],
    "LEARNING": ["L", "ER1", "N", "IH0", "NG"],
    "WONDER": ["W", "AH1", "N", "D", "ER0"], "WONDERS": ["W", "AH1", "N", "D", "ER0", "Z"],
    "WONDERED": ["W", "AH1", "N", "D", "ER0", "D"], "WONDERING": ["W", "AH1", "N", "D", "ER0", "IH0", "NG"],
    "DREAM": ["D", "R", "IY1", "M"], "DREAMS": ["D", "R", "IY1", "M", "Z"],
    "DREAMED": ["D", "R", "IY1", "M", "D"], "DREAMING": ["D", "R", "IY1", "M", "IH0", "NG"],
    "HOPE": ["HH", "OW1", "P"], "HOPES": ["HH", "OW1", "P", "S"], "HOPED": ["HH", "OW1", "P", "T"],
    "HOPING": ["HH", "OW1", "P", "IH0", "NG"],
    "WISH": ["W", "IH1", "SH"], "WISHES": ["W", "IH1", "SH", "IH0", "Z"],
    "WISHED": ["W", "IH1", "SH", "T"], "WISHING": ["W", "IH1", "SH", "IH0", "NG"],
    "WANT": ["W", "AA1", "N", "T"], "WANTS": ["W", "AA1", "N", "T", "S"],
    "WANTED": ["W", "AA1", "N", "T", "IH0", "D"], "WANTING": ["W", "AA1", "N", "T", "IH0", "NG"],
    "NEED": ["N", "IY1", "D"], "NEEDS": ["N", "IY1", "D", "Z"],
    "NEEDED": ["N", "IY1", "D", "IH0", "D"], "NEEDING": ["N", "IY1", "D", "IH0", "NG"],
    "TRY": ["T", "R", "AY1"], "TRIES": ["T", "R", "AY1", "Z"], "TRIED": ["T", "R", "AY1", "D"],
    "TRYING": ["T", "R", "AY1", "IH0", "NG"],
    "MEAN": ["M", "IY1", "N"], "MEANS": ["M", "IY1", "N", "Z"], "MEANT": ["M", "EH1", "N", "T"],
    "MEANING": ["M", "IY1", "N", "IH0", "NG"],
    "SEEM": ["S", "IY1", "M"], "SEEMS": ["S", "IY1", "M", "Z"], "SEEMED": ["S", "IY1", "M", "D"],
    "SEEMING": ["S", "IY1", "M", "IH0", "NG"],
    # Emotional actions
    "LOVE": ["L", "AH1", "V"], "LOVES": ["L", "AH1", "V", "Z"], "LOVED": ["L", "AH1", "V", "D"],
    "LOVING": ["L", "AH1", "V", "IH0", "NG"],
    "HATE": ["HH", "EY1", "T"], "HATES": ["HH", "EY1", "T", "S"],
    "HATED": ["HH", "EY1", "T", "IH0", "D"], "HATING": ["HH", "EY1", "T", "IH0", "NG"],
    "LIKE": ["L", "AY1", "K"], "LIKES": ["L", "AY1", "K", "S"], "LIKED": ["L", "AY1", "K", "T"],
    "LIKING": ["L", "AY1", "K", "IH0", "NG"],
    "MISS": ["M", "IH1", "S"], "MISSES": ["M", "IH1", "S", "IH0", "Z"],
    "MISSED": ["M", "IH1", "S", "T"], "MISSING": ["M", "IH1", "S", "IH0", "NG"],
    "HURT": ["HH", "ER1", "T"], "HURTS": ["HH", "ER1", "T", "S"], "HURTING": ["HH", "ER1", "T", "IH0", "NG"],
    "CARE": ["K", "EH1", "R"], "CARES": ["K", "EH1", "R", "Z"], "CARED": ["K", "EH1", "R", "D"],
    "CARING": ["K", "EH1", "R", "IH0", "NG"],
    "TRUST": ["T", "R", "AH1", "S", "T"], "TRUSTS": ["T", "R", "AH1", "S", "T", "S"],
    "TRUSTED": ["T", "R", "AH1", "S", "T", "IH0", "D"], "TRUSTING": ["T", "R", "AH1", "S", "T", "IH0", "NG"],
    "FEAR": ["F", "IH1", "R"], "FEARS": ["F", "IH1", "R", "Z"], "FEARED": ["F", "IH1", "R", "D"],
    "FEARING": ["F", "IH1", "R", "IH0", "NG"],
    # Creation/destruction
    "CREATE": ["K", "R", "IY0", "EY1", "T"], "CREATES": ["K", "R", "IY0", "EY1", "T", "S"],
    "CREATED": ["K", "R", "IY0", "EY1", "T", "IH0", "D"],
    "CREATING": ["K", "R", "IY0", "EY1", "T", "IH0", "NG"],
    "BUILD": ["B", "IH1", "L", "D"], "BUILDS": ["B", "IH1", "L", "D", "Z"],
    "BUILT": ["B", "IH1", "L", "T"], "BUILDING": ["B", "IH1", "L", "D", "IH0", "NG"],
    "BREAK": ["B", "R", "EY1", "K"], "BREAKS": ["B", "R", "EY1", "K", "S"],
    "BROKE": ["B", "R", "OW1", "K"], "BROKEN": ["B", "R", "OW1", "K", "AH0", "N"],
    "BREAKING": ["B", "R", "EY1", "K", "IH0", "NG"],
    "CHANGE": ["CH", "EY1", "N", "JH"], "CHANGES": ["CH", "EY1", "N", "JH", "IH0", "Z"],
    "CHANGED": ["CH", "EY1", "N", "JH", "D"], "CHANGING": ["CH", "EY1", "N", "JH", "IH0", "NG"],
    "GROW": ["G", "R", "OW1"], "GROWS": ["G", "R", "OW1", "Z"], "GREW": ["G", "R", "UW1"],
    "GROWN": ["G", "R", "OW1", "N"], "GROWING": ["G", "R", "OW1", "IH0", "NG"],
    "DIE": ["D", "AY1"], "DIES": ["D", "AY1", "Z"], "DIED": ["D", "AY1", "D"],
    "DYING": ["D", "AY1", "IH0", "NG"],
    "KILL": ["K", "IH1", "L"], "KILLS": ["K", "IH1", "L", "Z"], "KILLED": ["K", "IH1", "L", "D"],
    "KILLING": ["K", "IH1", "L", "IH0", "NG"],
    "SAVE": ["S", "EY1", "V"], "SAVES": ["S", "EY1", "V", "Z"], "SAVED": ["S", "EY1", "V", "D"],
    "SAVING": ["S", "EY1", "V", "IH0", "NG"],
    "LOSE": ["L", "UW1", "Z"], "LOSES": ["L", "UW1", "Z", "IH0", "Z"], "LOST": ["L", "AO1", "S", "T"],
    "LOSING": ["L", "UW1", "Z", "IH0", "NG"],
    "FIND": ["F", "AY1", "N", "D"], "FINDS": ["F", "AY1", "N", "D", "Z"],
    "FOUND": ["F", "AW1", "N", "D"], "FINDING": ["F", "AY1", "N", "D", "IH0", "NG"],
    "GIVE": ["G", "IH1", "V"], "GIVES": ["G", "IH1", "V", "Z"], "GAVE": ["G", "EY1", "V"],
    "GIVEN": ["G", "IH1", "V", "AH0", "N"], "GIVING": ["G", "IH1", "V", "IH0", "NG"],
    "TAKE": ["T", "EY1", "K"], "TAKES": ["T", "EY1", "K", "S"], "TOOK": ["T", "UH1", "K"],
    "TAKEN": ["T", "EY1", "K", "AH0", "N"], "TAKING": ["T", "EY1", "K", "IH0", "NG"],
    "SEND": ["S", "EH1", "N", "D"], "SENDS": ["S", "EH1", "N", "D", "Z"],
    "SENT": ["S", "EH1", "N", "T"], "SENDING": ["S", "EH1", "N", "D", "IH0", "NG"],
    "BRING": ["B", "R", "IH1", "NG"], "BRINGS": ["B", "R", "IH1", "NG", "Z"],
    "BROUGHT": ["B", "R", "AO1", "T"], "BRINGING": ["B", "R", "IH1", "NG", "IH0", "NG"],
    "SHOW": ["SH", "OW1"], "SHOWS": ["SH", "OW1", "Z"], "SHOWED": ["SH", "OW1", "D"],
    "SHOWN": ["SH", "OW1", "N"], "SHOWING": ["SH", "OW1", "IH0", "NG"],
    "HIDE": ["HH", "AY1", "D"], "HIDES": ["HH", "AY1", "D", "Z"], "HID": ["HH", "IH1", "D"],
    "HIDDEN": ["HH", "IH1", "D", "AH0", "N"], "HIDING": ["HH", "AY1", "D", "IH0", "NG"],
    "OPEN": ["OW1", "P", "AH0", "N"], "OPENS": ["OW1", "P", "AH0", "N", "Z"],
    "OPENED": ["OW1", "P", "AH0", "N", "D"], "OPENING": ["OW1", "P", "AH0", "N", "IH0", "NG"],
    "CLOSE": ["K", "L", "OW1", "Z"], "CLOSES": ["K", "L", "OW1", "Z", "IH0", "Z"],
    "CLOSED": ["K", "L", "OW1", "Z", "D"], "CLOSING": ["K", "L", "OW1", "Z", "IH0", "NG"],
    "START": ["S", "T", "AA1", "R", "T"], "STARTS": ["S", "T", "AA1", "R", "T", "S"],
    "STARTED": ["S", "T", "AA1", "R", "T", "IH0", "D"], "STARTING": ["S", "T", "AA1", "R", "T", "IH0", "NG"],
    "STOP": ["S", "T", "AA1", "P"], "STOPS": ["S", "T", "AA1", "P", "S"],
    "STOPPED": ["S", "T", "AA1", "P", "T"], "STOPPING": ["S", "T", "AA1", "P", "IH0", "NG"],
    "END": ["EH1", "N", "D"], "ENDS": ["EH1", "N", "D", "Z"],
    "ENDED": ["EH1", "N", "D", "IH0", "D"], "ENDING": ["EH1", "N", "D", "IH0", "NG"],
    "BEGIN": ["B", "IH0", "G", "IH1", "N"], "BEGINS": ["B", "IH0", "G", "IH1", "N", "Z"],
    "BEGAN": ["B", "IH0", "G", "AE1", "N"], "BEGUN": ["B", "IH0", "G", "AH1", "N"],
    "BEGINNING": ["B", "IH0", "G", "IH1", "N", "IH0", "NG"],
    "WAIT": ["W", "EY1", "T"], "WAITS": ["W", "EY1", "T", "S"],
    "WAITED": ["W", "EY1", "T", "IH0", "D"], "WAITING": ["W", "EY1", "T", "IH0", "NG"],
    "WORK": ["W", "ER1", "K"], "WORKS": ["W", "ER1", "K", "S"], "WORKED": ["W", "ER1", "K", "T"],
    "WORKING": ["W", "ER1", "K", "IH0", "NG"],
    "PLAY": ["P", "L", "EY1"], "PLAYS": ["P", "L", "EY1", "Z"], "PLAYED": ["P", "L", "EY1", "D"],
    "PLAYING": ["P", "L", "EY1", "IH0", "NG"],
    "LIVE": ["L", "IH1", "V"], "LIVES": ["L", "IH1", "V", "Z"], "LIVED": ["L", "IH1", "V", "D"],
    "LIVING": ["L", "IH1", "V", "IH0", "NG"],
    "SLEEP": ["S", "L", "IY1", "P"], "SLEEPS": ["S", "L", "IY1", "P", "S"],
    "SLEPT": ["S", "L", "EH1", "P", "T"], "SLEEPING": ["S", "L", "IY1", "P", "IH0", "NG"],
    "WAKE": ["W", "EY1", "K"], "WAKES": ["W", "EY1", "K", "S"], "WOKE": ["W", "OW1", "K"],
    "WOKEN": ["W", "OW1", "K", "AH0", "N"], "WAKING": ["W", "EY1", "K", "IH0", "NG"],
    "EAT": ["IY1", "T"], "EATS": ["IY1", "T", "S"], "ATE": ["EY1", "T"],
    "EATEN": ["IY1", "T", "AH0", "N"], "EATING": ["IY1", "T", "IH0", "NG"],
    "DRINK": ["D", "R", "IH1", "NG", "K"], "DRINKS": ["D", "R", "IH1", "NG", "K", "S"],
    "DRANK": ["D", "R", "AE1", "NG", "K"], "DRUNK": ["D", "R", "AH1", "NG", "K"],
    "DRINKING": ["D", "R", "IH1", "NG", "K", "IH0", "NG"],
    "BURN": ["B", "ER1", "N"], "BURNS": ["B", "ER1", "N", "Z"], "BURNED": ["B", "ER1", "N", "D"],
    "BURNT": ["B", "ER1", "N", "T"], "BURNING": ["B", "ER1", "N", "IH0", "NG"],
    "SHINE": ["SH", "AY1", "N"], "SHINES": ["SH", "AY1", "N", "Z"], "SHONE": ["SH", "OW1", "N"],
    "SHINING": ["SH", "AY1", "N", "IH0", "NG"],
    "FIGHT": ["F", "AY1", "T"], "FIGHTS": ["F", "AY1", "T", "S"], "FOUGHT": ["F", "AO1", "T"],
    "FIGHTING": ["F", "AY1", "T", "IH0", "NG"],
    "WIN": ["W", "IH1", "N"], "WINS": ["W", "IH1", "N", "Z"], "WON": ["W", "AH1", "N"],
    "WINNING": ["W", "IH1", "N", "IH0", "NG"],
    "BEAT": ["B", "IY1", "T"], "BEATS": ["B", "IY1", "T", "S"], "BEATING": ["B", "IY1", "T", "IH0", "NG"],
    "HIT": ["HH", "IH1", "T"], "HITS": ["HH", "IH1", "T", "S"], "HITTING": ["HH", "IH1", "T", "IH0", "NG"],
    "CUT": ["K", "AH1", "T"], "CUTS": ["K", "AH1", "T", "S"], "CUTTING": ["K", "AH1", "T", "IH0", "NG"],
    "WEAR": ["W", "EH1", "R"], "WEARS": ["W", "EH1", "R", "Z"], "WORE": ["W", "AO1", "R"],
    "WORN": ["W", "AO1", "R", "N"], "WEARING": ["W", "EH1", "R", "IH0", "NG"],
    "DRAW": ["D", "R", "AO1"], "DRAWS": ["D", "R", "AO1", "Z"], "DREW": ["D", "R", "UW1"],
    "DRAWN": ["D", "R", "AO1", "N"], "DRAWING": ["D", "R", "AO1", "IH0", "NG"],
    "CHOOSE": ["CH", "UW1", "Z"], "CHOOSES": ["CH", "UW1", "Z", "IH0", "Z"],
    "CHOSE": ["CH", "OW1", "Z"], "CHOSEN": ["CH", "OW1", "Z", "AH0", "N"],
    "CHOOSING": ["CH", "UW1", "Z", "IH0", "NG"],
    "DECIDE": ["D", "IH0", "S", "AY1", "D"], "DECIDES": ["D", "IH0", "S", "AY1", "D", "Z"],
    "DECIDED": ["D", "IH0", "S", "AY1", "D", "IH0", "D"],
    "DECIDING": ["D", "IH0", "S", "AY1", "D", "IH0", "NG"],
    "MEET": ["M", "IY1", "T"], "MEETS": ["M", "IY1", "T", "S"], "MET": ["M", "EH1", "T"],
    "MEETING": ["M", "IY1", "T", "IH0", "NG"],
    "PAY": ["P", "EY1"], "PAYS": ["P", "EY1", "Z"], "PAID": ["P", "EY1", "D"],
    "PAYING": ["P", "EY1", "IH0", "NG"],
    "BUY": ["B", "AY1"], "BUYS": ["B", "AY1", "Z"], "BOUGHT": ["B", "AO1", "T"],
    "BUYING": ["B", "AY1", "IH0", "NG"],
    "SELL": ["S", "EH1", "L"], "SELLS": ["S", "EH1", "L", "Z"], "SOLD": ["S", "OW1", "L", "D"],
    "SELLING": ["S", "EH1", "L", "IH0", "NG"],
    "SPEND": ["S", "P", "EH1", "N", "D"], "SPENDS": ["S", "P", "EH1", "N", "D", "Z"],
    "SPENT": ["S", "P", "EH1", "N", "T"], "SPENDING": ["S", "P", "EH1", "N", "D", "IH0", "NG"],
    "PRAY": ["P", "R", "EY1"], "PRAYS": ["P", "R", "EY1", "Z"], "PRAYED": ["P", "R", "EY1", "D"],
    "PRAYING": ["P", "R", "EY1", "IH0", "NG"],
}

# =============================================================================
# EMOTIONS & FEELINGS (Critical for songwriting)
# =============================================================================

_EMOTIONS: Dict[str, List[str]] = {
    "HAPPY": ["HH", "AE1", "P", "IY0"], "HAPPINESS": ["HH", "AE1", "P", "IY0", "N", "AH0", "S"],
    "SAD": ["S", "AE1", "D"], "SADNESS": ["S", "AE1", "D", "N", "AH0", "S"],
    "ANGRY": ["AE1", "NG", "G", "R", "IY0"], "ANGER": ["AE1", "NG", "G", "ER0"],
    "AFRAID": ["AH0", "F", "R", "EY1", "D"], "SCARED": ["S", "K", "EH1", "R", "D"],
    "LONELY": ["L", "OW1", "N", "L", "IY0"], "ALONE": ["AH0", "L", "OW1", "N"],
    "TIRED": ["T", "AY1", "ER0", "D"], "SICK": ["S", "IH1", "K"],
    "LOST": ["L", "AO1", "S", "T"], "CONFUSED": ["K", "AH0", "N", "F", "Y", "UW1", "Z", "D"],
    "CRAZY": ["K", "R", "EY1", "Z", "IY0"],
    "FREE": ["F", "R", "IY1"], "FREEDOM": ["F", "R", "IY1", "D", "AH0", "M"],
    "PEACE": ["P", "IY1", "S"], "PEACEFUL": ["P", "IY1", "S", "F", "AH0", "L"],
    "CALM": ["K", "AA1", "M"], "QUIET": ["K", "W", "AY1", "AH0", "T"],
    "SILENT": ["S", "AY1", "L", "AH0", "N", "T"], "SILENCE": ["S", "AY1", "L", "AH0", "N", "S"],
    "LOVER": ["L", "AH1", "V", "ER0"], "LOVELY": ["L", "AH1", "V", "L", "IY0"],
    "BELOVED": ["B", "IH0", "L", "AH1", "V", "D"],
    "HEART": ["HH", "AA1", "R", "T"], "HEARTS": ["HH", "AA1", "R", "T", "S"],
    "HEARTBREAK": ["HH", "AA1", "R", "T", "B", "R", "EY2", "K"],
    "HEARTBROKEN": ["HH", "AA1", "R", "T", "B", "R", "OW2", "K", "AH0", "N"],
    "PASSION": ["P", "AE1", "SH", "AH0", "N"], "DESIRE": ["D", "IH0", "Z", "AY1", "R"],
    "LONGING": ["L", "AO1", "NG", "IH0", "NG"], "TENDER": ["T", "EH1", "N", "D", "ER0"],
    "SWEET": ["S", "W", "IY1", "T"], "GENTLE": ["JH", "EH1", "N", "T", "AH0", "L"],
    "KIND": ["K", "AY1", "N", "D"], "KINDNESS": ["K", "AY1", "N", "D", "N", "AH0", "S"],
    "WARM": ["W", "AO1", "R", "M"], "WARMTH": ["W", "AO1", "R", "M", "TH"],
    "SAFE": ["S", "EY1", "F"], "COMFORT": ["K", "AH1", "M", "F", "ER0", "T"],
    "HOME": ["HH", "OW1", "M"], "BELONG": ["B", "IH0", "L", "AO1", "NG"],
    "BELONGING": ["B", "IH0", "L", "AO1", "NG", "IH0", "NG"],
    "PAIN": ["P", "EY1", "N"], "PAINFUL": ["P", "EY1", "N", "F", "AH0", "L"],
    "SORROW": ["S", "AA1", "R", "OW0"], "GRIEF": ["G", "R", "IY1", "F"],
    "REGRET": ["R", "IH0", "G", "R", "EH1", "T"], "SHAME": ["SH", "EY1", "M"],
    "GUILT": ["G", "IH1", "L", "T"], "GUILTY": ["G", "IH1", "L", "T", "IY0"],
    "BLAME": ["B", "L", "EY1", "M"],
    "SUFFER": ["S", "AH1", "F", "ER0"], "SUFFERING": ["S", "AH1", "F", "ER0", "IH0", "NG"],
    "TEAR": ["T", "IH1", "R"], "TEARS": ["T", "IH1", "R", "Z"],
    "WEEP": ["W", "IY1", "P"], "WEEPING": ["W", "IY1", "P", "IH0", "NG"],
    "WOUND": ["W", "UW1", "N", "D"], "WOUNDED": ["W", "UW1", "N", "D", "IH0", "D"],
    "SCAR": ["S", "K", "AA1", "R"], "SCARS": ["S", "K", "AA1", "R", "Z"],
    "SCARRED": ["S", "K", "AA1", "R", "D"],
    "BROKEN": ["B", "R", "OW1", "K", "AH0", "N"], "EMPTY": ["EH1", "M", "P", "T", "IY0"],
    "HOLLOW": ["HH", "AA1", "L", "OW0"], "NUMB": ["N", "AH1", "M"],
    "COLD": ["K", "OW1", "L", "D"],
    "JOY": ["JH", "OY1"], "JOYFUL": ["JH", "OY1", "F", "AH0", "L"],
    "HOPEFUL": ["HH", "OW1", "P", "F", "AH0", "L"], "HOPELESS": ["HH", "OW1", "P", "L", "AH0", "S"],
    "FAITH": ["F", "EY1", "TH"], "FAITHFUL": ["F", "EY1", "TH", "F", "AH0", "L"],
    "BELIEF": ["B", "IH0", "L", "IY1", "F"],
    "BLESSED": ["B", "L", "EH1", "S", "T"], "BLESSING": ["B", "L", "EH1", "S", "IH0", "NG"],
    "GRACE": ["G", "R", "EY1", "S"], "GRATEFUL": ["G", "R", "EY1", "T", "F", "AH0", "L"],
    "THANKFUL": ["TH", "AE1", "NG", "K", "F", "AH0", "L"],
    "GLAD": ["G", "L", "AE1", "D"], "PROUD": ["P", "R", "AW1", "D"],
    "PRIDE": ["P", "R", "AY1", "D"], "BRAVE": ["B", "R", "EY1", "V"],
    "STRONG": ["S", "T", "R", "AO1", "NG"], "STRENGTH": ["S", "T", "R", "EH1", "NG", "K", "TH"],
    "POWER": ["P", "AW1", "ER0"], "POWERFUL": ["P", "AW1", "ER0", "F", "AH0", "L"],
    "YEARN": ["Y", "ER1", "N"], "YEARNING": ["Y", "ER1", "N", "IH0", "NG"],
    "ACHE": ["EY1", "K"], "ACHING": ["EY1", "K", "IH0", "NG"],
    "HUNGER": ["HH", "AH1", "NG", "G", "ER0"], "THIRST": ["TH", "ER1", "S", "T"],
    "CRAVE": ["K", "R", "EY1", "V"], "CRAVING": ["K", "R", "EY1", "V", "IH0", "NG"],
    "SEARCH": ["S", "ER1", "CH"], "SEARCHING": ["S", "ER1", "CH", "IH0", "NG"],
    "SEEK": ["S", "IY1", "K"], "SEEKING": ["S", "IY1", "K", "IH0", "NG"],
    "WONDERFUL": ["W", "AH1", "N", "D", "ER0", "F", "AH0", "L"],
    "AMAZING": ["AH0", "M", "EY1", "Z", "IH0", "NG"],
    "MAGIC": ["M", "AE1", "JH", "IH0", "K"], "MAGICAL": ["M", "AE1", "JH", "IH0", "K", "AH0", "L"],
    "MYSTERY": ["M", "IH1", "S", "T", "ER0", "IY0"], "MIRACLE": ["M", "IH1", "R", "AH0", "K", "AH0", "L"],
    "BEAUTIFUL": ["B", "Y", "UW1", "T", "AH0", "F", "AH0", "L"], "BEAUTY": ["B", "Y", "UW1", "T", "IY0"],
    "GLORY": ["G", "L", "AO1", "R", "IY0"], "GLORIOUS": ["G", "L", "AO1", "R", "IY0", "AH0", "S"],
    "HEAVEN": ["HH", "EH1", "V", "AH0", "N"], "HEAVENLY": ["HH", "EH1", "V", "AH0", "N", "L", "IY0"],
    "DIVINE": ["D", "IH0", "V", "AY1", "N"], "SACRED": ["S", "EY1", "K", "R", "IH0", "D"],
    "HOLY": ["HH", "OW1", "L", "IY0"],
    "SPIRIT": ["S", "P", "IH1", "R", "IH0", "T"], "SOUL": ["S", "OW1", "L"], "SOULS": ["S", "OW1", "L", "Z"],
}

# =============================================================================
# TIME & TEMPORAL WORDS
# =============================================================================

_TIME_WORDS: Dict[str, List[str]] = {
    "DAY": ["D", "EY1"], "DAYS": ["D", "EY1", "Z"],
    "TODAY": ["T", "AH0", "D", "EY1"], "TOMORROW": ["T", "AH0", "M", "AA1", "R", "OW0"],
    "YESTERDAY": ["Y", "EH1", "S", "T", "ER0", "D", "EY2"],
    "MORNING": ["M", "AO1", "R", "N", "IH0", "NG"], "AFTERNOON": ["AE2", "F", "T", "ER0", "N", "UW1", "N"],
    "EVENING": ["IY1", "V", "N", "IH0", "NG"],
    "NIGHT": ["N", "AY1", "T"], "NIGHTS": ["N", "AY1", "T", "S"],
    "TONIGHT": ["T", "AH0", "N", "AY1", "T"], "MIDNIGHT": ["M", "IH1", "D", "N", "AY2", "T"],
    "DAWN": ["D", "AO1", "N"], "DUSK": ["D", "AH1", "S", "K"],
    "SUNRISE": ["S", "AH1", "N", "R", "AY2", "Z"], "SUNSET": ["S", "AH1", "N", "S", "EH2", "T"],
    "WEEK": ["W", "IY1", "K"], "WEEKS": ["W", "IY1", "K", "S"],
    "MONTH": ["M", "AH1", "N", "TH"], "MONTHS": ["M", "AH1", "N", "TH", "S"],
    "YEAR": ["Y", "IH1", "R"], "YEARS": ["Y", "IH1", "R", "Z"],
    "DECADE": ["D", "EH1", "K", "EY0", "D"], "CENTURY": ["S", "EH1", "N", "CH", "ER0", "IY0"],
    "LIFETIME": ["L", "AY1", "F", "T", "AY2", "M"], "ETERNITY": ["IH0", "T", "ER1", "N", "IH0", "T", "IY0"],
    "SPRING": ["S", "P", "R", "IH1", "NG"], "SUMMER": ["S", "AH1", "M", "ER0"],
    "AUTUMN": ["AO1", "T", "AH0", "M"], "WINTER": ["W", "IH1", "N", "T", "ER0"],
    "SEASON": ["S", "IY1", "Z", "AH0", "N"], "SEASONS": ["S", "IY1", "Z", "AH0", "N", "Z"],
    "MOMENT": ["M", "OW1", "M", "AH0", "N", "T"], "SECOND": ["S", "EH1", "K", "AH0", "N", "D"],
    "MINUTE": ["M", "IH1", "N", "AH0", "T"],
    "HOUR": ["AW1", "ER0"], "HOURS": ["AW1", "ER0", "Z"],
    "TIME": ["T", "AY1", "M"], "TIMES": ["T", "AY1", "M", "Z"],
    "PAST": ["P", "AE1", "S", "T"], "PRESENT": ["P", "R", "EH1", "Z", "AH0", "N", "T"],
    "FUTURE": ["F", "Y", "UW1", "CH", "ER0"],
    "HISTORY": ["HH", "IH1", "S", "T", "ER0", "IY0"],
    "MEMORY": ["M", "EH1", "M", "ER0", "IY0"], "MEMORIES": ["M", "EH1", "M", "ER0", "IY0", "Z"],
    "YOUNG": ["Y", "AH1", "NG"], "OLD": ["OW1", "L", "D"],
    "AGE": ["EY1", "JH"], "AGES": ["EY1", "JH", "IH0", "Z"],
    "CHILD": ["CH", "AY1", "L", "D"], "CHILDREN": ["CH", "IH1", "L", "D", "R", "AH0", "N"],
    "BABY": ["B", "EY1", "B", "IY0"], "YOUTH": ["Y", "UW1", "TH"],
    "DEATH": ["D", "EH1", "TH"], "DEAD": ["D", "EH1", "D"],
    "BIRTH": ["B", "ER1", "TH"], "BORN": ["B", "AO1", "R", "N"],
    "LIFE": ["L", "AY1", "F"],
}

# =============================================================================
# NATURE & ENVIRONMENT
# =============================================================================

_NATURE: Dict[str, List[str]] = {
    "SKY": ["S", "K", "AY1"], "SKIES": ["S", "K", "AY1", "Z"],
    "SUN": ["S", "AH1", "N"], "SUNSHINE": ["S", "AH1", "N", "SH", "AY2", "N"],
    "SUNLIGHT": ["S", "AH1", "N", "L", "AY2", "T"],
    "MOON": ["M", "UW1", "N"], "MOONLIGHT": ["M", "UW1", "N", "L", "AY2", "T"],
    "STAR": ["S", "T", "AA1", "R"], "STARS": ["S", "T", "AA1", "R", "Z"],
    "STARLIGHT": ["S", "T", "AA1", "R", "L", "AY2", "T"],
    "CLOUD": ["K", "L", "AW1", "D"], "CLOUDS": ["K", "L", "AW1", "D", "Z"],
    "RAINBOW": ["R", "EY1", "N", "B", "OW2"],
    "LIGHT": ["L", "AY1", "T"], "LIGHTS": ["L", "AY1", "T", "S"],
    "DARK": ["D", "AA1", "R", "K"], "DARKNESS": ["D", "AA1", "R", "K", "N", "AH0", "S"],
    "SHADOW": ["SH", "AE1", "D", "OW0"], "SHADOWS": ["SH", "AE1", "D", "OW0", "Z"],
    "RAIN": ["R", "EY1", "N"], "RAINS": ["R", "EY1", "N", "Z"], "RAINING": ["R", "EY1", "N", "IH0", "NG"],
    "STORM": ["S", "T", "AO1", "R", "M"], "STORMS": ["S", "T", "AO1", "R", "M", "Z"],
    "THUNDER": ["TH", "AH1", "N", "D", "ER0"], "LIGHTNING": ["L", "AY1", "T", "N", "IH0", "NG"],
    "SNOW": ["S", "N", "OW1"], "SNOWING": ["S", "N", "OW1", "IH0", "NG"],
    "ICE": ["AY1", "S"], "FREEZE": ["F", "R", "IY1", "Z"], "FROZEN": ["F", "R", "OW1", "Z", "AH0", "N"],
    "WIND": ["W", "IH1", "N", "D"], "WINDS": ["W", "IH1", "N", "D", "Z"],
    "BREEZE": ["B", "R", "IY1", "Z"], "FOG": ["F", "AA1", "G"], "MIST": ["M", "IH1", "S", "T"],
    "HEAT": ["HH", "IY1", "T"], "HOT": ["HH", "AA1", "T"],
    "EARTH": ["ER1", "TH"], "LAND": ["L", "AE1", "N", "D"],
    "GROUND": ["G", "R", "AW1", "N", "D"], "DIRT": ["D", "ER1", "T"],
    "DUST": ["D", "AH1", "S", "T"], "MUD": ["M", "AH1", "D"],
    "SAND": ["S", "AE1", "N", "D"],
    "STONE": ["S", "T", "OW1", "N"], "STONES": ["S", "T", "OW1", "N", "Z"],
    "ROCK": ["R", "AA1", "K"], "ROCKS": ["R", "AA1", "K", "S"],
    "MOUNTAIN": ["M", "AW1", "N", "T", "AH0", "N"], "MOUNTAINS": ["M", "AW1", "N", "T", "AH0", "N", "Z"],
    "HILL": ["HH", "IH1", "L"], "HILLS": ["HH", "IH1", "L", "Z"],
    "VALLEY": ["V", "AE1", "L", "IY0"], "VALLEYS": ["V", "AE1", "L", "IY0", "Z"],
    "FIELD": ["F", "IY1", "L", "D"], "FIELDS": ["F", "IY1", "L", "D", "Z"],
    "MEADOW": ["M", "EH1", "D", "OW0"], "DESERT": ["D", "EH1", "Z", "ER0", "T"],
    "FOREST": ["F", "AO1", "R", "AH0", "S", "T"], "WOODS": ["W", "UH1", "D", "Z"],
    "GARDEN": ["G", "AA1", "R", "D", "AH0", "N"],
    "WATER": ["W", "AO1", "T", "ER0"], "WATERS": ["W", "AO1", "T", "ER0", "Z"],
    "RIVER": ["R", "IH1", "V", "ER0"], "RIVERS": ["R", "IH1", "V", "ER0", "Z"],
    "STREAM": ["S", "T", "R", "IY1", "M"], "CREEK": ["K", "R", "IY1", "K"],
    "LAKE": ["L", "EY1", "K"], "LAKES": ["L", "EY1", "K", "S"],
    "POND": ["P", "AA1", "N", "D"], "OCEAN": ["OW1", "SH", "AH0", "N"],
    "SEA": ["S", "IY1"], "SEAS": ["S", "IY1", "Z"],
    "WAVE": ["W", "EY1", "V"], "WAVES": ["W", "EY1", "V", "Z"],
    "TIDE": ["T", "AY1", "D"], "TIDES": ["T", "AY1", "D", "Z"],
    "SHORE": ["SH", "AO1", "R"], "BEACH": ["B", "IY1", "CH"],
    "COAST": ["K", "OW1", "S", "T"], "ISLAND": ["AY1", "L", "AH0", "N", "D"],
    "TREE": ["T", "R", "IY1"], "TREES": ["T", "R", "IY1", "Z"],
    "LEAF": ["L", "IY1", "F"], "LEAVES": ["L", "IY1", "V", "Z"],
    "BRANCH": ["B", "R", "AE1", "N", "CH"], "BRANCHES": ["B", "R", "AE1", "N", "CH", "IH0", "Z"],
    "ROOT": ["R", "UW1", "T"], "ROOTS": ["R", "UW1", "T", "S"],
    "FLOWER": ["F", "L", "AW1", "ER0"], "FLOWERS": ["F", "L", "AW1", "ER0", "Z"],
    "ROSE": ["R", "OW1", "Z"], "ROSES": ["R", "OW1", "Z", "IH0", "Z"],
    "PETAL": ["P", "EH1", "T", "AH0", "L"], "PETALS": ["P", "EH1", "T", "AH0", "L", "Z"],
    "BLOOM": ["B", "L", "UW1", "M"], "BLOOMING": ["B", "L", "UW1", "M", "IH0", "NG"],
    "SEED": ["S", "IY1", "D"], "SEEDS": ["S", "IY1", "D", "Z"],
    "GRASS": ["G", "R", "AE1", "S"],
    "VINE": ["V", "AY1", "N"], "VINES": ["V", "AY1", "N", "Z"],
    "THORN": ["TH", "AO1", "R", "N"], "THORNS": ["TH", "AO1", "R", "N", "Z"],
    "FIRE": ["F", "AY1", "ER0"], "FIRES": ["F", "AY1", "ER0", "Z"],
    "FLAME": ["F", "L", "EY1", "M"], "FLAMES": ["F", "L", "EY1", "M", "Z"],
    "SMOKE": ["S", "M", "OW1", "K"],
    "ASH": ["AE1", "SH"], "ASHES": ["AE1", "SH", "IH0", "Z"],
    "EMBER": ["EH1", "M", "B", "ER0"], "EMBERS": ["EH1", "M", "B", "ER0", "Z"],
    "SPARK": ["S", "P", "AA1", "R", "K"], "SPARKS": ["S", "P", "AA1", "R", "K", "S"],
    "AIR": ["EH1", "R"], "BREATH": ["B", "R", "EH1", "TH"],
    "BREATHE": ["B", "R", "IY1", "DH"], "BREATHING": ["B", "R", "IY1", "DH", "IH0", "NG"],
}

# =============================================================================
# BODY PARTS
# =============================================================================

_BODY: Dict[str, List[str]] = {
    "HEAD": ["HH", "EH1", "D"], "FACE": ["F", "EY1", "S"], "FACES": ["F", "EY1", "S", "IH0", "Z"],
    "EYE": ["AY1"], "EYES": ["AY1", "Z"],
    "EAR": ["IH1", "R"], "EARS": ["IH1", "R", "Z"],
    "NOSE": ["N", "OW1", "Z"], "MOUTH": ["M", "AW1", "TH"],
    "LIP": ["L", "IH1", "P"], "LIPS": ["L", "IH1", "P", "S"],
    "TONGUE": ["T", "AH1", "NG"], "TOOTH": ["T", "UW1", "TH"], "TEETH": ["T", "IY1", "TH"],
    "CHIN": ["CH", "IH1", "N"], "CHEEK": ["CH", "IY1", "K"], "CHEEKS": ["CH", "IY1", "K", "S"],
    "HAIR": ["HH", "EH1", "R"], "BROW": ["B", "R", "AW1"],
    "BODY": ["B", "AA1", "D", "IY0"], "BODIES": ["B", "AA1", "D", "IY0", "Z"],
    "SKIN": ["S", "K", "IH1", "N"], "BONE": ["B", "OW1", "N"], "BONES": ["B", "OW1", "N", "Z"],
    "BLOOD": ["B", "L", "AH1", "D"], "FLESH": ["F", "L", "EH1", "SH"],
    "CHEST": ["CH", "EH1", "S", "T"], "BACK": ["B", "AE1", "K"],
    "SHOULDER": ["SH", "OW1", "L", "D", "ER0"], "SHOULDERS": ["SH", "OW1", "L", "D", "ER0", "Z"],
    "NECK": ["N", "EH1", "K"], "THROAT": ["TH", "R", "OW1", "T"],
    "ARM": ["AA1", "R", "M"], "ARMS": ["AA1", "R", "M", "Z"],
    "HAND": ["HH", "AE1", "N", "D"], "HANDS": ["HH", "AE1", "N", "D", "Z"],
    "FINGER": ["F", "IH1", "NG", "G", "ER0"], "FINGERS": ["F", "IH1", "NG", "G", "ER0", "Z"],
    "FIST": ["F", "IH1", "S", "T"], "FISTS": ["F", "IH1", "S", "T", "S"],
    "PALM": ["P", "AA1", "M"], "PALMS": ["P", "AA1", "M", "Z"],
    "LEG": ["L", "EH1", "G"], "LEGS": ["L", "EH1", "G", "Z"],
    "FOOT": ["F", "UH1", "T"], "FEET": ["F", "IY1", "T"],
    "TOE": ["T", "OW1"], "TOES": ["T", "OW1", "Z"],
    "KNEE": ["N", "IY1"], "KNEES": ["N", "IY1", "Z"],
    "VOICE": ["V", "OY1", "S"], "VOICES": ["V", "OY1", "S", "IH0", "Z"],
    "WING": ["W", "IH1", "NG"], "WINGS": ["W", "IH1", "NG", "Z"],
}

# =============================================================================
# PLACES & STRUCTURES
# =============================================================================

_PLACES: Dict[str, List[str]] = {
    "HOUSE": ["HH", "AW1", "S"], "HOUSES": ["HH", "AW1", "Z", "IH0", "Z"],
    "HOMES": ["HH", "OW1", "M", "Z"],
    "ROOM": ["R", "UW1", "M"], "ROOMS": ["R", "UW1", "M", "Z"],
    "DOOR": ["D", "AO1", "R"], "DOORS": ["D", "AO1", "R", "Z"],
    "WINDOW": ["W", "IH1", "N", "D", "OW0"], "WINDOWS": ["W", "IH1", "N", "D", "OW0", "Z"],
    "WALL": ["W", "AO1", "L"], "WALLS": ["W", "AO1", "L", "Z"],
    "FLOOR": ["F", "L", "AO1", "R"], "FLOORS": ["F", "L", "AO1", "R", "Z"],
    "ROOF": ["R", "UW1", "F"], "CEILING": ["S", "IY1", "L", "IH0", "NG"],
    "STAIR": ["S", "T", "EH1", "R"], "STAIRS": ["S", "T", "EH1", "R", "Z"],
    "BED": ["B", "EH1", "D"], "BEDS": ["B", "EH1", "D", "Z"],
    "TABLE": ["T", "EY1", "B", "AH0", "L"],
    "CHAIR": ["CH", "EH1", "R"], "CHAIRS": ["CH", "EH1", "R", "Z"],
    "CHURCH": ["CH", "ER1", "CH"], "TEMPLE": ["T", "EH1", "M", "P", "AH0", "L"],
    "CASTLE": ["K", "AE1", "S", "AH0", "L"],
    "TOWER": ["T", "AW1", "ER0"], "TOWERS": ["T", "AW1", "ER0", "Z"],
    "BRIDGE": ["B", "R", "IH1", "JH"], "BRIDGES": ["B", "R", "IH1", "JH", "IH0", "Z"],
    "GATE": ["G", "EY1", "T"], "GATES": ["G", "EY1", "T", "S"],
    "FENCE": ["F", "EH1", "N", "S"],
    "TOWN": ["T", "AW1", "N"], "CITY": ["S", "IH1", "T", "IY0"],
    "STREET": ["S", "T", "R", "IY1", "T"], "STREETS": ["S", "T", "R", "IY1", "T", "S"],
    "ROAD": ["R", "OW1", "D"], "ROADS": ["R", "OW1", "D", "Z"],
    "PATH": ["P", "AE1", "TH"], "PATHS": ["P", "AE1", "TH", "S"],
    "WAY": ["W", "EY1"], "WAYS": ["W", "EY1", "Z"],
    "HIGHWAY": ["HH", "AY1", "W", "EY2"], "CORNER": ["K", "AO1", "R", "N", "ER0"],
    "PLACE": ["P", "L", "EY1", "S"], "PLACES": ["P", "L", "EY1", "S", "IH0", "Z"],
    "WORLD": ["W", "ER1", "L", "D"], "WORLDS": ["W", "ER1", "L", "D", "Z"],
    "COUNTRY": ["K", "AH1", "N", "T", "R", "IY0"], "STATE": ["S", "T", "EY1", "T"],
    "NATION": ["N", "EY1", "SH", "AH0", "N"], "BORDER": ["B", "AO1", "R", "D", "ER0"],
    "NORTH": ["N", "AO1", "R", "TH"], "SOUTH": ["S", "AW1", "TH"],
    "EAST": ["IY1", "S", "T"], "WEST": ["W", "EH1", "S", "T"],
    "DISTANCE": ["D", "IH1", "S", "T", "AH0", "N", "S"], "EDGE": ["EH1", "JH"],
    "CENTER": ["S", "EH1", "N", "T", "ER0"], "MIDDLE": ["M", "IH1", "D", "AH0", "L"],
    "SIDE": ["S", "AY1", "D"], "SIDES": ["S", "AY1", "D", "Z"],
}

# =============================================================================
# RELATIONSHIPS & PEOPLE
# =============================================================================

_RELATIONSHIPS: Dict[str, List[str]] = {
    "FAMILY": ["F", "AE1", "M", "AH0", "L", "IY0"],
    "FATHER": ["F", "AA1", "DH", "ER0"], "MOTHER": ["M", "AH1", "DH", "ER0"],
    "PARENT": ["P", "EH1", "R", "AH0", "N", "T"], "PARENTS": ["P", "EH1", "R", "AH0", "N", "T", "S"],
    "SON": ["S", "AH1", "N"], "SONS": ["S", "AH1", "N", "Z"],
    "DAUGHTER": ["D", "AO1", "T", "ER0"], "DAUGHTERS": ["D", "AO1", "T", "ER0", "Z"],
    "BROTHER": ["B", "R", "AH1", "DH", "ER0"], "BROTHERS": ["B", "R", "AH1", "DH", "ER0", "Z"],
    "SISTER": ["S", "IH1", "S", "T", "ER0"], "SISTERS": ["S", "IH1", "S", "T", "ER0", "Z"],
    "BABIES": ["B", "EY1", "B", "IY0", "Z"],
    "HUSBAND": ["HH", "AH1", "Z", "B", "AH0", "N", "D"], "WIFE": ["W", "AY1", "F"],
    "GRANDMA": ["G", "R", "AE1", "N", "D", "M", "AA2"], "GRANDPA": ["G", "R", "AE1", "N", "D", "P", "AA2"],
    "GRANDMOTHER": ["G", "R", "AE1", "N", "D", "M", "AH2", "DH", "ER0"],
    "GRANDFATHER": ["G", "R", "AE1", "N", "D", "F", "AA2", "DH", "ER0"],
    "UNCLE": ["AH1", "NG", "K", "AH0", "L"], "AUNT": ["AE1", "N", "T"],
    "COUSIN": ["K", "AH1", "Z", "AH0", "N"],
    "LOVERS": ["L", "AH1", "V", "ER0", "Z"],
    "DARLING": ["D", "AA1", "R", "L", "IH0", "NG"], "DEAR": ["D", "IH1", "R"],
    "SWEETHEART": ["S", "W", "IY1", "T", "HH", "AA2", "R", "T"],
    "HONEY": ["HH", "AH1", "N", "IY0"], "BABE": ["B", "EY1", "B"],
    "ANGEL": ["EY1", "N", "JH", "AH0", "L"], "ANGELS": ["EY1", "N", "JH", "AH0", "L", "Z"],
    "FRIEND": ["F", "R", "EH1", "N", "D"], "FRIENDS": ["F", "R", "EH1", "N", "D", "Z"],
    "ENEMY": ["EH1", "N", "AH0", "M", "IY0"], "ENEMIES": ["EH1", "N", "AH0", "M", "IY0", "Z"],
    "STRANGER": ["S", "T", "R", "EY1", "N", "JH", "ER0"], "STRANGERS": ["S", "T", "R", "EY1", "N", "JH", "ER0", "Z"],
    "NEIGHBOR": ["N", "EY1", "B", "ER0"], "NEIGHBORS": ["N", "EY1", "B", "ER0", "Z"],
    "PEOPLE": ["P", "IY1", "P", "AH0", "L"], "PERSON": ["P", "ER1", "S", "AH0", "N"],
    "SOMEBODY": ["S", "AH1", "M", "B", "AA2", "D", "IY0"],
    "EVERYBODY": ["EH1", "V", "R", "IY0", "B", "AA2", "D", "IY0"],
    "ANYBODY": ["EH1", "N", "IY0", "B", "AA2", "D", "IY0"],
    "CROWD": ["K", "R", "AW1", "D"],
    "MAN": ["M", "AE1", "N"], "MEN": ["M", "EH1", "N"],
    "WOMAN": ["W", "UH1", "M", "AH0", "N"], "WOMEN": ["W", "IH1", "M", "AH0", "N"],
    "BOY": ["B", "OY1"], "BOYS": ["B", "OY1", "Z"],
    "GIRL": ["G", "ER1", "L"], "GIRLS": ["G", "ER1", "L", "Z"],
    "GUY": ["G", "AY1"], "GUYS": ["G", "AY1", "Z"],
    "KING": ["K", "IH1", "NG"], "QUEEN": ["K", "W", "IY1", "N"],
    "PRINCE": ["P", "R", "IH1", "N", "S"], "PRINCESS": ["P", "R", "IH1", "N", "S", "EH0", "S"],
    "LORD": ["L", "AO1", "R", "D"], "GOD": ["G", "AA1", "D"],
    "DEVIL": ["D", "EH1", "V", "AH0", "L"],
    "GHOST": ["G", "OW1", "S", "T"], "GHOSTS": ["G", "OW1", "S", "T", "S"],
    "HERO": ["HH", "IH1", "R", "OW0"], "HEROES": ["HH", "IH1", "R", "OW0", "Z"],
    "FOOL": ["F", "UW1", "L"], "FOOLS": ["F", "UW1", "L", "Z"],
    "SAINT": ["S", "EY1", "N", "T"],
    "SINNER": ["S", "IH1", "N", "ER0"], "SINNERS": ["S", "IH1", "N", "ER0", "Z"],
}

# =============================================================================
# COLORS & ADJECTIVES
# =============================================================================

_COLORS: Dict[str, List[str]] = {
    "BLACK": ["B", "L", "AE1", "K"], "WHITE": ["W", "AY1", "T"],
    "RED": ["R", "EH1", "D"], "BLUE": ["B", "L", "UW1"],
    "GREEN": ["G", "R", "IY1", "N"], "YELLOW": ["Y", "EH1", "L", "OW0"],
    "ORANGE": ["AO1", "R", "AH0", "N", "JH"], "PURPLE": ["P", "ER1", "P", "AH0", "L"],
    "PINK": ["P", "IH1", "NG", "K"], "BROWN": ["B", "R", "AW1", "N"],
    "GRAY": ["G", "R", "EY1"], "GREY": ["G", "R", "EY1"],
    "GOLD": ["G", "OW1", "L", "D"], "GOLDEN": ["G", "OW1", "L", "D", "AH0", "N"],
    "SILVER": ["S", "IH1", "L", "V", "ER0"],
    "BRIGHT": ["B", "R", "AY1", "T"], "PALE": ["P", "EY1", "L"], "DEEP": ["D", "IY1", "P"],
}

_ADJECTIVES: Dict[str, List[str]] = {
    "BIG": ["B", "IH1", "G"], "SMALL": ["S", "M", "AO1", "L"],
    "LARGE": ["L", "AA1", "R", "JH"], "LITTLE": ["L", "IH1", "T", "AH0", "L"],
    "TINY": ["T", "AY1", "N", "IY0"], "HUGE": ["HH", "Y", "UW1", "JH"],
    "GREAT": ["G", "R", "EY1", "T"], "TALL": ["T", "AO1", "L"], "SHORT": ["SH", "AO1", "R", "T"],
    "LONG": ["L", "AO1", "NG"], "WIDE": ["W", "AY1", "D"], "NARROW": ["N", "AE1", "R", "OW0"],
    "THICK": ["TH", "IH1", "K"], "THIN": ["TH", "IH1", "N"],
    "FAT": ["F", "AE1", "T"], "HEAVY": ["HH", "EH1", "V", "IY0"],
    "FULL": ["F", "UH1", "L"],
    "GOOD": ["G", "UH1", "D"], "BAD": ["B", "AE1", "D"],
    "BEST": ["B", "EH1", "S", "T"], "WORST": ["W", "ER1", "S", "T"],
    "BETTER": ["B", "EH1", "T", "ER0"], "WORSE": ["W", "ER1", "S"],
    "RIGHT": ["R", "AY1", "T"], "WRONG": ["R", "AO1", "NG"],
    "TRUE": ["T", "R", "UW1"], "FALSE": ["F", "AO1", "L", "S"],
    "REAL": ["R", "IY1", "L"], "FAKE": ["F", "EY1", "K"],
    "PERFECT": ["P", "ER1", "F", "IH0", "K", "T"], "PURE": ["P", "Y", "UH1", "R"],
    "CLEAN": ["K", "L", "IY1", "N"], "DIRTY": ["D", "ER1", "T", "IY0"],
    "CLEAR": ["K", "L", "IH1", "R"], "FRESH": ["F", "R", "EH1", "SH"],
    "NICE": ["N", "AY1", "S"], "FINE": ["F", "AY1", "N"], "COOL": ["K", "UW1", "L"],
    "STRANGE": ["S", "T", "R", "EY1", "N", "JH"], "WEIRD": ["W", "IH1", "R", "D"],
    "WILD": ["W", "AY1", "L", "D"],
    "HARD": ["HH", "AA1", "R", "D"], "SOFT": ["S", "AO1", "F", "T"],
    "ROUGH": ["R", "AH1", "F"], "SMOOTH": ["S", "M", "UW1", "DH"],
    "SHARP": ["SH", "AA1", "R", "P"], "DULL": ["D", "AH1", "L"],
    "WET": ["W", "EH1", "T"], "DRY": ["D", "R", "AY1"],
    "FAST": ["F", "AE1", "S", "T"], "SLOW": ["S", "L", "OW1"], "QUICK": ["K", "W", "IH1", "K"],
    "HIGH": ["HH", "AY1"], "LOW": ["L", "OW1"],
    "LOUD": ["L", "AW1", "D"],
    "NEW": ["N", "UW1"],
    "ANCIENT": ["EY1", "N", "SH", "AH0", "N", "T"], "MODERN": ["M", "AA1", "D", "ER0", "N"],
    "ALIVE": ["AH0", "L", "AY1", "V"], "AWAKE": ["AH0", "W", "EY1", "K"],
    "ASLEEP": ["AH0", "S", "L", "IY1", "P"],
    "SHUT": ["SH", "AH1", "T"], "NAKED": ["N", "EY1", "K", "IH0", "D"], "BARE": ["B", "EH1", "R"],
    "WEAK": ["W", "IY1", "K"], "TOUGH": ["T", "AH1", "F"],
    "FIERCE": ["F", "IH1", "R", "S"], "BOLD": ["B", "OW1", "L", "D"], "SHY": ["SH", "AY1"],
    "HUMBLE": ["HH", "AH1", "M", "B", "AH0", "L"],
    "WISE": ["W", "AY1", "Z"], "SMART": ["S", "M", "AA1", "R", "T"],
    "DUMB": ["D", "AH1", "M"], "STUPID": ["S", "T", "UW1", "P", "IH0", "D"],
    "CLEVER": ["K", "L", "EH1", "V", "ER0"], "HONEST": ["AA1", "N", "AH0", "S", "T"],
    "LOYAL": ["L", "OY1", "AH0", "L"],
    "EVIL": ["IY1", "V", "AH0", "L"], "WICKED": ["W", "IH1", "K", "IH0", "D"],
    "CRUEL": ["K", "R", "UW1", "AH0", "L"],
    "PRETTY": ["P", "R", "IH1", "T", "IY0"], "HANDSOME": ["HH", "AE1", "N", "S", "AH0", "M"],
    "UGLY": ["AH1", "G", "L", "IY0"], "FAIR": ["F", "EH1", "R"],
}

# =============================================================================
# MUSIC & SOUND
# =============================================================================

_MUSIC: Dict[str, List[str]] = {
    "MUSIC": ["M", "Y", "UW1", "Z", "IH0", "K"],
    "SONG": ["S", "AO1", "NG"], "SONGS": ["S", "AO1", "NG", "Z"],
    "MELODY": ["M", "EH1", "L", "AH0", "D", "IY0"], "RHYTHM": ["R", "IH1", "DH", "AH0", "M"],
    "DRUM": ["D", "R", "AH1", "M"], "DRUMS": ["D", "R", "AH1", "M", "Z"],
    "GUITAR": ["G", "IH0", "T", "AA1", "R"], "PIANO": ["P", "IY0", "AE1", "N", "OW0"],
    "VIOLIN": ["V", "AY2", "AH0", "L", "IH1", "N"],
    "HORN": ["HH", "AO1", "R", "N"], "BELL": ["B", "EH1", "L"], "BELLS": ["B", "EH1", "L", "Z"],
    "SOUND": ["S", "AW1", "N", "D"], "SOUNDS": ["S", "AW1", "N", "D", "Z"],
    "NOISE": ["N", "OY1", "Z"],
    "ECHO": ["EH1", "K", "OW0"], "RING": ["R", "IH1", "NG"], "RINGING": ["R", "IH1", "NG", "IH0", "NG"],
}

# =============================================================================
# ABSTRACT CONCEPTS
# =============================================================================

_ABSTRACT: Dict[str, List[str]] = {
    "TRUTH": ["T", "R", "UW1", "TH"], "DOUBT": ["D", "AW1", "T"],
    "FATE": ["F", "EY1", "T"], "LUCK": ["L", "AH1", "K"],
    "CHANCE": ["CH", "AE1", "N", "S"], "CHOICE": ["CH", "OY1", "S"],
    "LOSS": ["L", "AO1", "S"], "GAIN": ["G", "EY1", "N"],
    "GAME": ["G", "EY1", "M"], "RISK": ["R", "IH1", "S", "K"],
    "PRICE": ["P", "R", "AY1", "S"], "COST": ["K", "AO1", "S", "T"],
    "VALUE": ["V", "AE1", "L", "Y", "UW0"], "WORTH": ["W", "ER1", "TH"],
    "PROMISE": ["P", "R", "AA1", "M", "AH0", "S"],
    "SECRET": ["S", "IY1", "K", "R", "AH0", "T"], "SECRETS": ["S", "IY1", "K", "R", "AH0", "T", "S"],
    "HONOR": ["AA1", "N", "ER0"],
    "SIN": ["S", "IH1", "N"], "SINS": ["S", "IH1", "N", "Z"],
    "MERCY": ["M", "ER1", "S", "IY0"], "JUSTICE": ["JH", "AH1", "S", "T", "IH0", "S"],
    "WAR": ["W", "AO1", "R"],
    "MIND": ["M", "AY1", "N", "D"],
    "THOUGHTS": ["TH", "AO1", "T", "S"], "IDEA": ["AY0", "D", "IY1", "AH0"],
    "WORD": ["W", "ER1", "D"], "WORDS": ["W", "ER1", "D", "Z"],
    "NAME": ["N", "EY1", "M"], "NAMES": ["N", "EY1", "M", "Z"],
    "STORY": ["S", "T", "AO1", "R", "IY0"], "STORIES": ["S", "T", "AO1", "R", "IY0", "Z"],
    "TALE": ["T", "EY1", "L"], "TALES": ["T", "EY1", "L", "Z"],
    "LEGEND": ["L", "EH1", "JH", "AH0", "N", "D"], "MYTH": ["M", "IH1", "TH"],
}

# =============================================================================
# NUMBERS & QUANTITIES
# =============================================================================

_NUMBERS: Dict[str, List[str]] = {
    "ZERO": ["Z", "IY1", "R", "OW0"], "ONE": ["W", "AH1", "N"],
    "TWO": ["T", "UW1"], "THREE": ["TH", "R", "IY1"],
    "FOUR": ["F", "AO1", "R"], "FIVE": ["F", "AY1", "V"],
    "SIX": ["S", "IH1", "K", "S"], "SEVEN": ["S", "EH1", "V", "AH0", "N"],
    "EIGHT": ["EY1", "T"], "NINE": ["N", "AY1", "N"], "TEN": ["T", "EH1", "N"],
    "ELEVEN": ["IH0", "L", "EH1", "V", "AH0", "N"], "TWELVE": ["T", "W", "EH1", "L", "V"],
    "THIRTEEN": ["TH", "ER0", "T", "IY1", "N"], "TWENTY": ["T", "W", "EH1", "N", "T", "IY0"],
    "THIRTY": ["TH", "ER1", "T", "IY0"], "FORTY": ["F", "AO1", "R", "T", "IY0"],
    "FIFTY": ["F", "IH1", "F", "T", "IY0"],
    "HUNDRED": ["HH", "AH1", "N", "D", "R", "AH0", "D"],
    "THOUSAND": ["TH", "AW1", "Z", "AH0", "N", "D"],
    "MILLION": ["M", "IH1", "L", "Y", "AH0", "N"],
    "FIRST": ["F", "ER1", "S", "T"], "THIRD": ["TH", "ER1", "D"],
    "LAST": ["L", "AE1", "S", "T"], "HALF": ["HH", "AE1", "F"],
    "QUARTER": ["K", "W", "AO1", "R", "T", "ER0"],
    "DOUBLE": ["D", "AH1", "B", "AH0", "L"], "TRIPLE": ["T", "R", "IH1", "P", "AH0", "L"],
    "SINGLE": ["S", "IH1", "NG", "G", "AH0", "L"],
    "PAIR": ["P", "EH1", "R"], "COUPLE": ["K", "AH1", "P", "AH0", "L"],
}

# =============================================================================
# CONTRACTIONS & INFORMAL SPEECH
# =============================================================================

_CONTRACTIONS: Dict[str, List[str]] = {
    # Negative contractions
    "DIDNT": ["D", "IH1", "D", "AH0", "N", "T"], "DONT": ["D", "OW1", "N", "T"],
    "WONT": ["W", "OW1", "N", "T"], "CANT": ["K", "AE1", "N", "T"],
    "ISNT": ["IH1", "Z", "AH0", "N", "T"], "ARENT": ["AA1", "R", "AH0", "N", "T"],
    "WASNT": ["W", "AA1", "Z", "AH0", "N", "T"], "WERENT": ["W", "ER1", "AH0", "N", "T"],
    "HAVENT": ["HH", "AE1", "V", "AH0", "N", "T"], "HASNT": ["HH", "AE1", "Z", "AH0", "N", "T"],
    "HADNT": ["HH", "AE1", "D", "AH0", "N", "T"],
    "WOULDNT": ["W", "UH1", "D", "AH0", "N", "T"], "COULDNT": ["K", "UH1", "D", "AH0", "N", "T"],
    "SHOULDNT": ["SH", "UH1", "D", "AH0", "N", "T"],
    # 've contractions
    "IVE": ["AY1", "V"], "YOUVE": ["Y", "UW1", "V"], "WEVE": ["W", "IY1", "V"],
    "THEYVE": ["DH", "EY1", "V"],
    "WOULDVE": ["W", "UH1", "D", "AH0", "V"], "COULDVE": ["K", "UH1", "D", "AH0", "V"],
    "SHOULDVE": ["SH", "UH1", "D", "AH0", "V"],
    # 're contractions
    "YOURE": ["Y", "UH1", "R"], "THEYRE": ["DH", "EH1", "R"],
    # 'll contractions
    "ILL": ["AY1", "L"], "YOULL": ["Y", "UW1", "L"], "HELL": ["HH", "IY1", "L"],
    "SHELL": ["SH", "IY1", "L"], "THEYLL": ["DH", "EY1", "L"],
    "ITLL": ["IH1", "T", "AH0", "L"], "THATLL": ["DH", "AE1", "T", "AH0", "L"],
    # 'd contractions
    "ID": ["AY1", "D"], "YOUD": ["Y", "UW1", "D"], "HED": ["HH", "IY1", "D"],
    "SHED": ["SH", "IY1", "D"], "WED": ["W", "IY1", "D"], "THEYD": ["DH", "EY1", "D"],
    # 's contractions
    "HERES": ["HH", "IH1", "R", "Z"], "THERES": ["DH", "EH1", "R", "Z"],
    "WHERES": ["W", "EH1", "R", "Z"], "THATS": ["DH", "AE1", "T", "S"],
    "WHATS": ["W", "AH1", "T", "S"], "WHOS": ["HH", "UW1", "Z"],
    "HOWS": ["HH", "AW1", "Z"],
    # Informal -in' endings
    "GOIN": ["G", "OW1", "IH0", "N"], "COMIN": ["K", "AH1", "M", "IH0", "N"],
    "RUNNIN": ["R", "AH1", "N", "IH0", "N"], "WALKIN": ["W", "AO1", "K", "IH0", "N"],
    "TALKIN": ["T", "AO1", "K", "IH0", "N"], "STANDIN": ["S", "T", "AE1", "N", "D", "IH0", "N"],
    "SITTIN": ["S", "IH1", "T", "IH0", "N"], "GETTIN": ["G", "EH1", "T", "IH0", "N"],
    "SINGIN": ["S", "IH1", "NG", "IH0", "N"], "BRINGIN": ["B", "R", "IH1", "NG", "IH0", "N"],
    "DANCIN": ["D", "AE1", "N", "S", "IH0", "N"], "LOVIN": ["L", "AH1", "V", "IH0", "N"],
    "LIVIN": ["L", "IH1", "V", "IH0", "N"], "GIVIN": ["G", "IH1", "V", "IH0", "N"],
    "DRIVIN": ["D", "R", "AY1", "V", "IH0", "N"], "MOVIN": ["M", "UW1", "V", "IH0", "N"],
    "THINKIN": ["TH", "IH1", "NG", "K", "IH0", "N"], "DRINKIN": ["D", "R", "IH1", "NG", "K", "IH0", "N"],
    "SLEEPIN": ["S", "L", "IY1", "P", "IH0", "N"], "KEEPIN": ["K", "IY1", "P", "IH0", "N"],
    "PRAYIN": ["P", "R", "EY1", "IH0", "N"], "SAYIN": ["S", "EY1", "IH0", "N"],
    "PLAYIN": ["P", "L", "EY1", "IH0", "N"], "STAYIN": ["S", "T", "EY1", "IH0", "N"],
    "LAYIN": ["L", "EY1", "IH0", "N"], "PAYIN": ["P", "EY1", "IH0", "N"],
    "WAITIN": ["W", "EY1", "T", "IH0", "N"], "HATIN": ["HH", "EY1", "T", "IH0", "N"],
    "MAKIN": ["M", "EY1", "K", "IH0", "N"], "TAKIN": ["T", "EY1", "K", "IH0", "N"],
    "SHAKIN": ["SH", "EY1", "K", "IH0", "N"], "WAKIN": ["W", "EY1", "K", "IH0", "N"],
    "BREAKIN": ["B", "R", "EY1", "K", "IH0", "N"], "CRYIN": ["K", "R", "AY1", "IH0", "N"],
    "DYIN": ["D", "AY1", "IH0", "N"], "LYIN": ["L", "AY1", "IH0", "N"],
    "TRYIN": ["T", "R", "AY1", "IH0", "N"], "FLYIN": ["F", "L", "AY1", "IH0", "N"],
    "FIGHTIN": ["F", "AY1", "T", "IH0", "N"], "WRITIN": ["R", "AY1", "T", "IH0", "N"],
    "RIDIN": ["R", "AY1", "D", "IH0", "N"], "HIDIN": ["HH", "AY1", "D", "IH0", "N"],
    "SHININ": ["SH", "AY1", "N", "IH0", "N"], "BURNIN": ["B", "ER1", "N", "IH0", "N"],
    "TURNIN": ["T", "ER1", "N", "IH0", "N"], "LEARNIN": ["L", "ER1", "N", "IH0", "N"],
    "WORKIN": ["W", "ER1", "K", "IH0", "N"], "HURTIN": ["HH", "ER1", "T", "IH0", "N"],
    "HOLDIN": ["HH", "OW1", "L", "D", "IH0", "N"], "ROLLIN": ["R", "OW1", "L", "IH0", "N"],
    "KNOWIN": ["N", "OW1", "IH0", "N"], "SHOWIN": ["SH", "OW1", "IH0", "N"],
    "GROWIN": ["G", "R", "OW1", "IH0", "N"], "BLOWIN": ["B", "L", "OW1", "IH0", "N"],
    "FLOWIN": ["F", "L", "OW1", "IH0", "N"], "THROWIN": ["TH", "R", "OW1", "IH0", "N"],
    "FALLIN": ["F", "AO1", "L", "IH0", "N"], "CALLIN": ["K", "AO1", "L", "IH0", "N"],
    "PULLIN": ["P", "UH1", "L", "IH0", "N"], "PUSHIN": ["P", "UH1", "SH", "IH0", "N"],
    "LOOKIN": ["L", "UH1", "K", "IH0", "N"],
    "FEELIN": ["F", "IY1", "L", "IH0", "N"], "HEALIN": ["HH", "IY1", "L", "IH0", "N"],
    "DREAMIN": ["D", "R", "IY1", "M", "IH0", "N"], "SCREAMIN": ["S", "K", "R", "IY1", "M", "IH0", "N"],
    "LEAVIN": ["L", "IY1", "V", "IH0", "N"], "BELIEVIN": ["B", "IH0", "L", "IY1", "V", "IH0", "N"],
    "REACHIN": ["R", "IY1", "CH", "IH0", "N"], "TEACHIN": ["T", "IY1", "CH", "IH0", "N"],
    "BEGGIN": ["B", "EH1", "G", "IH0", "N"], "SETTIN": ["S", "EH1", "T", "IH0", "N"],
    "TELLIN": ["T", "EH1", "L", "IH0", "N"], "SELLIN": ["S", "EH1", "L", "IH0", "N"],
    "YELLIN": ["Y", "EH1", "L", "IH0", "N"], "SENDIN": ["S", "EH1", "N", "D", "IH0", "N"],
    "SPENDIN": ["S", "P", "EH1", "N", "D", "IH0", "N"], "ENDIN": ["EH1", "N", "D", "IH0", "N"],
    "WISHIN": ["W", "IH1", "SH", "IH0", "N"], "MISSIN": ["M", "IH1", "S", "IH0", "N"],
    "KISSIN": ["K", "IH1", "S", "IH0", "N"], "WINNIN": ["W", "IH1", "N", "IH0", "N"],
    "SPINNIN": ["S", "P", "IH1", "N", "IH0", "N"], "SWIMMIN": ["S", "W", "IH1", "M", "IH0", "N"],
    # Other informal
    "GONNA": ["G", "AH1", "N", "AH0"], "WANNA": ["W", "AA1", "N", "AH0"],
    "GOTTA": ["G", "AA1", "T", "AH0"], "KINDA": ["K", "AY1", "N", "D", "AH0"],
    "SORTA": ["S", "AO1", "R", "T", "AH0"], "OUTTA": ["AW1", "T", "AH0"],
    "LOTTA": ["L", "AA1", "T", "AH0"], "OUGHTA": ["AO1", "T", "AH0"],
    "COULDA": ["K", "UH1", "D", "AH0"], "WOULDA": ["W", "UH1", "D", "AH0"],
    "SHOULDA": ["SH", "UH1", "D", "AH0"], "MUSTA": ["M", "AH1", "S", "T", "AH0"],
    "LEMME": ["L", "EH1", "M", "IY0"], "GIMME": ["G", "IH1", "M", "IY0"],
    "GOTCHA": ["G", "AA1", "CH", "AH0"], "BETCHA": ["B", "EH1", "CH", "AH0"],
    "WHATCHA": ["W", "AH1", "CH", "AH0"],
    "YA": ["Y", "AH0"], "YEP": ["Y", "EH1", "P"], "YEAH": ["Y", "AE1"],
    "YUP": ["Y", "AH1", "P"], "NOPE": ["N", "OW1", "P"], "NAH": ["N", "AA1"],
    "HUH": ["HH", "AH1"], "UH": ["AH1"], "UM": ["AH1", "M"],
    "OK": ["OW2", "K", "EY1"], "OKAY": ["OW2", "K", "EY1"],
    "ALRIGHT": ["AO2", "L", "R", "AY1", "T"], "AINT": ["EY1", "N", "T"],
    "DUNNO": ["D", "AH0", "N", "OW1"],
    "CAUSE": ["K", "AH1", "Z"], "CUZ": ["K", "AH1", "Z"],
    "TIL": ["T", "IH1", "L"], "BOUT": ["B", "AW1", "T"], "EM": ["AH0", "M"],
}

# =============================================================================
# RHYME TEST WORDS (for validation)
# =============================================================================

_RHYME_TEST_WORDS: Dict[str, List[str]] = {
    # Perfect rhyme sets
    "CAT": ["K", "AE1", "T"], "HAT": ["HH", "AE1", "T"], "BAT": ["B", "AE1", "T"],
    "RAT": ["R", "AE1", "T"], "MAT": ["M", "AE1", "T"], "FLAT": ["F", "L", "AE1", "T"],
    # Plosive family rhymes (B/P, D/T, G/K)
    "RUB": ["R", "AH1", "B"], "TUB": ["T", "AH1", "B"], "CUB": ["K", "AH1", "B"],
    "CUP": ["K", "AH1", "P"], "SUP": ["S", "AH1", "P"],
    "BUD": ["B", "AH1", "D"], "THUD": ["TH", "AH1", "D"], "FLOOD": ["F", "L", "AH1", "D"],
    "GUT": ["G", "AH1", "T"], "HUT": ["HH", "AH1", "T"], "NUT": ["N", "AH1", "T"], "RUT": ["R", "AH1", "T"],
    "BUG": ["B", "AH1", "G"], "DUG": ["D", "AH1", "G"], "HUG": ["HH", "AH1", "G"],
    "JUG": ["JH", "AH1", "G"], "MUG": ["M", "AH1", "G"], "RUG": ["R", "AH1", "G"],
    "TUG": ["T", "AH1", "G"], "PLUG": ["P", "L", "AH1", "G"], "DRUG": ["D", "R", "AH1", "G"],
    "DUCK": ["D", "AH1", "K"], "STUCK": ["S", "T", "AH1", "K"], "TRUCK": ["T", "R", "AH1", "K"],
    # Fricative family rhymes (V/F, Z/S)
    "DOVE": ["D", "AH1", "V"], "SHOVE": ["SH", "AH1", "V"],
    "ENOUGH": ["IH0", "N", "AH1", "F"], "STUFF": ["S", "T", "AH1", "F"],
    "ROUGH": ["R", "AH1", "F"], "BLUFF": ["B", "L", "AH1", "F"], "BUFF": ["B", "AH1", "F"],
    "CUFF": ["K", "AH1", "F"], "PUFF": ["P", "AH1", "F"],
    # Nasal family rhymes (M/N/NG)
    "RUM": ["R", "AH1", "M"], "GUM": ["G", "AH1", "M"], "THUMB": ["TH", "AH1", "M"],
    "SOME": ["S", "AH1", "M"], "GUN": ["G", "AH1", "N"],
    "RUNG": ["R", "AH1", "NG"], "LUNG": ["L", "AH1", "NG"],
    # Assonance (OW vowel)
    "BONE": ["B", "OW1", "N"], "PHONE": ["F", "OW1", "N"], "TONE": ["T", "OW1", "N"],
    "ZONE": ["Z", "OW1", "N"], "THRONE": ["TH", "R", "OW1", "N"],
    "FLOW": ["F", "L", "OW1"], "GLOW": ["G", "L", "OW1"], "BLOW": ["B", "L", "OW1"],
    # Assonance (AY vowel)
    "LINE": ["L", "AY1", "N"], "WINE": ["W", "AY1", "N"], "SIGN": ["S", "AY1", "N"],
    "SPINE": ["S", "P", "AY1", "N"], "BITE": ["B", "AY1", "T"], "KITE": ["K", "AY1", "T"],
    "SITE": ["S", "AY1", "T"], "GUIDE": ["G", "AY1", "D"], "BRIDE": ["B", "R", "AY1", "D"],
    "STRIDE": ["S", "T", "R", "AY1", "D"], "GLIDE": ["G", "L", "AY1", "D"],
    "TIE": ["T", "AY1"], "PIE": ["P", "AY1"], "SIGH": ["S", "AY1"], "THIGH": ["TH", "AY1"],
    # Additive/Subtractive test
    "FREE": ["F", "R", "IY1"], "FREED": ["F", "R", "IY1", "D"],
    "SEE": ["S", "IY1"], "SEEN": ["S", "IY1", "N"], "SEEM": ["S", "IY1", "M"],
    "BEE": ["B", "IY1"], "BEAM": ["B", "IY1", "M"], "BEAD": ["B", "IY1", "D"], "BEAK": ["B", "IY1", "K"],
    "KEY": ["K", "IY1"], "KEEN": ["K", "IY1", "N"],
    "ME": ["M", "IY1"], "MEAL": ["M", "IY1", "L"],
    # Consonance test (different vowels, same consonants)
    "LEAVE": ["L", "IY1", "V"],
    "BID": ["B", "IH1", "D"], "BODE": ["B", "OW1", "D"],
}

# =============================================================================
# MERGE ALL DICTIONARIES
# =============================================================================

def get_builtin_cmu_dict() -> Dict[str, List[str]]:
    """
    Returns the complete built-in CMU dictionary.
    Merges all category dictionaries into a single dictionary.
    Each entry maps UPPERCASE word to list of ARPABET phonemes.
    """
    merged: Dict[str, List[str]] = {}
    
    categories = [
        _ARTICLES_PRONOUNS,
        _PREPOSITIONS_CONJUNCTIONS,
        _AUXILIARY_VERBS,
        _ACTION_VERBS,
        _EMOTIONS,
        _TIME_WORDS,
        _NATURE,
        _BODY,
        _PLACES,
        _RELATIONSHIPS,
        _COLORS,
        _ADJECTIVES,
        _MUSIC,
        _ABSTRACT,
        _NUMBERS,
        _CONTRACTIONS,
        _RHYME_TEST_WORDS,
    ]
    
    for category in categories:
        for word, phones in category.items():
            if word not in merged:
                merged[word] = phones
    
    return merged


# Export for use in PhoneticEngine
BUILTIN_CMU: Dict[str, List[str]] = get_builtin_cmu_dict()


def print_builtin_stats():
    """Print statistics about the built-in dictionary."""
    total = len(BUILTIN_CMU)
    print(f"Total words in built-in CMU dictionary: {total}")
    
    categories = {
        "Articles/Pronouns": len(_ARTICLES_PRONOUNS),
        "Prepositions/Conjunctions": len(_PREPOSITIONS_CONJUNCTIONS),
        "Auxiliary Verbs": len(_AUXILIARY_VERBS),
        "Action Verbs": len(_ACTION_VERBS),
        "Emotions": len(_EMOTIONS),
        "Time Words": len(_TIME_WORDS),
        "Nature": len(_NATURE),
        "Body Parts": len(_BODY),
        "Places": len(_PLACES),
        "Relationships": len(_RELATIONSHIPS),
        "Colors": len(_COLORS),
        "Adjectives": len(_ADJECTIVES),
        "Music": len(_MUSIC),
        "Abstract Concepts": len(_ABSTRACT),
        "Numbers": len(_NUMBERS),
        "Contractions/Informal": len(_CONTRACTIONS),
        "Rhyme Test Words": len(_RHYME_TEST_WORDS),
    }
    
    print("\nBy category:")
    for name, count in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"  {name}: {count}")


if __name__ == "__main__":
    print_builtin_stats()


# =============================================================================
# INTEGRATION HELPER
# =============================================================================

def integrate_with_phonetic_engine():
    """
    Example of how to integrate this with your existing PhoneticEngine.
    
    Replace the _BUILTIN_CMU in phonetic_engine.py with:
    
        from .builtin_cmu_expanded import BUILTIN_CMU as _BUILTIN_CMU
    
    Or merge it:
    
        from .builtin_cmu_expanded import BUILTIN_CMU
        
        # In PhoneticEngine.__init__:
        self._cmu.update({k: [v] for k, v in BUILTIN_CMU.items()})
    """
    pass